### ISSUE TITLE
Sprite shadows are now a GZDoom engine feature

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#515] opened 2021-04-25 14:52 UTC
@nashmuhandes's GZDoom engine-side sprite shadow code has been merged: https://github.com/coelckers/gzdoom/pull/1372

I would hold off on implementing this until after the April 30 release, however. We are too close to the release date.

**Comment by Username-N00b-is-not-available** [comment] 2021-04-25 14:53
Will it conflict with the existing BoA implementation? If not, removing the mod version from BoA could be left for 3.1.

**Comment by Talon1024** [comment] 2021-04-25 15:08
I hope not. If worse comes to worse, we can ship a GZDoom build from before the merge.

**Comment by x3003** [comment] 2021-04-25 15:15
Due to the saving bug, that version of gzdoom isn't shipped with boa anyway ?!

**Comment by Username-N00b-is-not-available** [comment] 2021-04-25 15:19
Nothing is established yet, the GZDoom developers can fix the saving bug before 30 April.

**Comment by Tormentor667** [comment] 2021-04-25 16:58
> I hope not. If worse comes to worse, we can ship a GZDoom build from before the merge.

I think we have made a decision regarding the version we will ship BoA with. I won't use a dev build that's released on 29th of April for a project, that is going to be released on 30th of April.

Regarding the shadow implementation: I'd leave that to a 3.1 version, if it is too complicated to take care of it now, but I'd let @Talon1024 and @AFADoomer decide.

**Comment by nashmuhandes** [comment] 2021-04-25 21:00
Yeah, don't use a devbuild for the first release of BoA. The engine-native sprite shadow would be completely absent and you can continue using the mod version.

As for how to [migrate](https://github.com/nashmuhandes/SpriteShadow/commit/aa02d86de4e189e1addff183884555a8566511f1) to the engine version, first up here's what you should know:

The way it works is that, by default, no sprite shadows are rendered. The engine will only draw sprite shadows under these 2 circumstances:

A) Actors are given a +CASTSPRITESHADOW flag. You can either do this on an actor-by-actor basis, or you can use [an event handler](https://github.com/nashmuhandes/SpriteShadow) (SpriteShadow v2.0 - to be released within the next few days - will use the latter, as a replacement for the previous versions of the mod).

B) The user themselves go to the Display menu, and set the "sprite shadow" setting to "always". This allows the user to force the engine to render sprite shadows for any living things.

The (A) method allows mods to specifically define which actors will render sprite shadows, without user intervention. (A) is most likely what BoA would want to do in future.

**Comment by Talon1024** [comment] 2021-05-03 19:26
I have begun work on this in the [feature/gzshadows](https://github.com/Realm667/WolfenDoom/tree/feature/gzshadows) branch.

**Comment by AFADoomer** [comment] 2021-05-12 02:36
These appear to work fine as designed, and are more efficient than the ZScript implementation.

Just wanted to note here that what we lose visually by switching to these versus the old ZScript ones are things that I had added to Nash's original implementation:
- Shadows would get larger and more translucent the higher an actor was above the ground, so flying enemies (or enemies on a catwalk above you) didn't just have a harshly-cast shadow below them - less like Duke, but that was the point.
- Shadows would fade away based on the the player approaching the shadow render distance (formerly boa_spriteshadowdistance) instead of just disappearing, so the shadow render distance could be lower and still look good.  

I don't think either of these can be replicated with the internal implementation.

**Comment by nashmuhandes** [comment] 2021-05-12 07:23
> These appear to work fine as designed, and are more efficient than the ZScript implementation.
> 
> Just wanted to note here that what we lose visually by switching to these versus the old ZScript ones are things that I had added to Nash's original implementation:
> 
> * Shadows would get larger and more translucent the higher an actor was above the ground, so flying enemies (or enemies on a catwalk above you) didn't just have a harshly-cast shadow below them - less like Duke, but that was the point.
> * Shadows would fade away based on the the player approaching the shadow render distance (formerly boa_spriteshadowdistance) instead of just disappearing, so the shadow render distance could be lower and still look good.
> 
> I don't think either of these can be replicated with the internal implementation.

Yes, you will lose your bespoke modifications with the engine native version. However, do keep in mind that the engine native version is made to be fast - the more features get added, the slower it'll become... the entire motivation to make it in-engine is so that it performs fast. :)

**Comment by Ozymandias81** [comment] 2021-05-12 20:30
Since I really doubt we need to add code just to replicate the old behavior, gzdoom shadows now works like a charm and they are finally present on Cutscene actors as well. Gonna close this, the only situation which may require playtesting is when Marlene Dietrich appears on HQs: when she leaves the theatre after a mission, make sure to check if shadows from decorative soldiers have been removed too.

**Closed by Ozymandias81** 2021-05-12 20:30 UTC
Labels: actor, discussion, enhancement / improvement
