### ISSUE TITLE
C1M0 issues

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#853] opened 2021-06-19 06:08 UTC
C1M0 ...

a) can clip into the tank at x 8251, y 2467.
b) Tanks cannon can clip through door at x 10369, y 2722.
c) Sector 793 - odd place for a telephone.
d) Wrong ceiling flat at sectors 4812 and 4813.
e) Wrong brightness level for sector 3923 ? Compare adjacent sectors.

**Comment by Talon1024** [comment] 2021-06-19 06:21
Duplicate of #854

**Closed by Talon1024** 2021-06-19 06:21 UTC

**Comment by Ozymandias81** [comment] 2021-06-19 11:55
b) is unavoidable. Fixed everything else.
