### ISSUE TITLE
Issues cross-posted from ModDB

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#566] opened 2021-05-03 14:51 UTC
- [x] Morgan0987 says that the combination safe in C1M4 is set to the wrong combination, specifically

<details><summary>combination</summary>
12-13-09 instead of 13-12-09.
</details>

Could someone please test it, @AFADoomer, @Talon1024? It is likely a false positive (as the arguments of thing 725 are in the correct order), but maybe the internal logic has changed...

Edit: another information source **confirms** that 13-12-09 does **not** work.

> The clues don't match the safe,, unkess you change to "US"-style month/day order..  Probably easiest to update the combo in the map. - AFA (3 May 21)

> OK, I see what they were doing...  The 'wrong' combo worked because the code fudges the values so that you can get "close enough" (within less than one number) and still open the safe.  Should be better now.  - AFA (4 May 21)

- [ ] A guest says that in the final battle Hitler was invisible for them... Again.

> Here is a photo of dead invisible Hitler from that person (I raised brighteness on it, it was almost pitch-black): --N00b, 03 May 2021

![Boa](https://user-images.githubusercontent.com/59409713/116925909-7be04580-ac62-11eb-8e27-d8aaead3a71a.jpg)

> Added an attempted fix for this.  - AFA (4 May 21)

- [x] Invisible wall in C1M2 vent: https://streamable.com/4pjwm2

> How did they even get up there? - AFA (3 May 21)

> Likely as in Ozymandias81's or MuadDib90's post. (I would personally use the former method, though unlimited sprint is definitely not necessary for that). --N00b, 3 May 2021
Ah, got an answer from them:
```
I jumped on the moving "super soldier" or whatever they are crates from above and then jumped into the vent, which was visible even earlier when I cleared the bottom floor. I had no idea grenade jumping was even a thing in this game
```

**Comment by Ozymandias81** [comment] 2021-05-03 16:52
Regarding [C1M2](https://github.com/Realm667/WolfenDoom/commit/703f8a43bee7da01c47ee6c19e56e3ce9d65b577#diff-a99f0afeb713bbe4b8afe75f99405dd2906516a8ce063fecfa10990efae80375), I [added this](https://imgbb.com/SJwS2FM) some days before release because you would be able to cut the map by grenade-jumping over there from the lower part, and the blocking line is unblocked once we press the button inside scientists room upstairs, where the bridge is. What to do then? I recall someone raised it to avoid skipping a portion of the map. And AFA is right, how does one can get there? Unlimited sprint and jump over the wall from above through the grate?

**Comment by Tormentor667** [comment] 2021-05-03 17:00
The code is working, you simply need to read it properly in the right order as it is written in the message - **13-12-09** - and it works.

**Comment by MuadDib90** [comment] 2021-05-03 17:00
**Regarding the combination:**

It worked for me at the weekend while in long run play. Tried it also just now.
The 
<details>
<summary>combination</summary>

13-12-09
</details>

works prefectly. Maybe they just misunderstood how the lock works. Otherwise I can't imagine...
Important thing: Were they able to reproduce it multiple times again and again?
I couldn't get the combination other than in _< details >_. And by turning left, right, left; according to the arrows.


**Regarding C1M2 issue:**

I was able to get there without cheats too. By jumping from those moving crates. It is hard, but doable. I also reported it as too hard to get for the key, because some time ago it was on the ground level. But when @Username-N00b-is-not-available  told me it is possible to get the key from the lowest level, I didn't borther to lose time by trying to jump over there...

**Comment by Username-N00b-is-not-available** [comment] 2021-05-03 17:04
@AFADoomer The map actor seems to have the arguments in proper order (just open the map in a text editor and search for `Cartridge51`):
<details><summary>Thing 725</summary>

```
thing // 725
{
x = 3232.0;
y = 3736.0;
angle = 95;
type = 32114;
arg0 = 9;
arg1 = 13;
arg2 = 12;
arg3 = 9;
skill1 = true;
skill2 = true;
skill3 = true;
skill4 = true;
skill5 = true;
skill6 = true;
skill7 = true;
skill8 = true;
single = true;
coop = true;
dm = true;
class1 = true;
class2 = true;
class3 = true;
class4 = true;
class5 = true;
arg0str = "Cartridge51";
}
```

</details>

**Comment by Username-N00b-is-not-available** [comment] 2021-05-03 18:16
For C1M2, the player who reported it suggests we add a visual barrier which is removed after the scientists' switch has been flipped. Maybe just a grate with a different texture?

**Comment by MuadDib90** [comment] 2021-05-03 18:38
Interesting...
When I start first turn left (counter-clockwise / as you are suppose to) both combinations are functional.
<details>
<summary>combinations</summary>

intended one 13-12-9
also unintended 12-13-9
</details>

But if I start to turn right (clockwise), only the supposed one is working

<details>
<summary>combination</summary>

this intended one 13-12-9
</details>

So, I guess this is an internal code based handler problem I can't help with.

**Comment by Username-N00b-is-not-available** [comment] 2021-05-03 18:43
Yes, I just got a message from the original poster with this video: https://www.moddb.com/members/toomuchcoffee/videos/boa
@AFADoomer Could you please also add a working check that the directions are to be in exactly that order as indicated by the hint? The check that is present currently does not seem to work correctly.

**Comment by AFADoomer** [comment] 2021-05-03 19:30
I'll probably try to make the dial spin only in one direction at the beginning, to make things easier.

**Comment by AFADoomer** [comment] 2021-05-04 05:22
Safes should be easier to use after 24d04e8353777b70ef393016408a638d3dbe61e2.

**Comment by Tormentor667** [comment] 2021-05-04 09:33
The safe works perfect now if you ask me.

**Comment by MuadDib90** [comment] 2021-05-04 18:15
> 
> 
> Safes should be easier to use after [24d04e8](https://github.com/Realm667/WolfenDoom/commit/24d04e8353777b70ef393016408a638d3dbe61e2).

I wanted to test it, but all I got from the latest commit (2a63b648782199e04b3e4438cd1b2a13676b7672) is this:
![Výstřižek](https://user-images.githubusercontent.com/73436978/117049646-b30f2f00-ad14-11eb-8e4b-801121367288.PNG)

**Comment by AFADoomer** [comment] 2021-05-04 18:26
You have to use a newer GZDoom dev build to use the built-in sprite shadows.

**Comment by Tormentor667** [comment] 2021-05-04 19:09
Exactly, you can get a new version from svn.drdteam.org

**Comment by Username-N00b-is-not-available** [comment] 2021-05-05 17:01
A new portion of problems on https://www.moddb.com/mods/wolfendoom-blade-of-agony/page/2#comments:
- [ ] In the release version, C1M3 once again seems to have killcount broken (195/197).
I asked the player (brianhellfire) to tell me the output of `netevent showliveenemies`.
- [ ] Performance issues, and for some reason the worst performance reports come from high-end hardware (1080gtx, 20xx, 30xx Nvidia series). Maybe it is just the survivorship bias, but I don't remember anybody from the developer team having such issues...

**Comment by Ozymandias81** [comment] 2021-05-05 17:19
I just hope they are using proper shipped version of GZDoom, for example pagb666 is using r199, and some played it from D-Touch, others streaming with several apps active in background I think... I wonder how much difference there would be from Win 10 to Win 7 too, Win 10 had already some funny happenings regarding [general stuttering](https://www.techtimes.com/articles/259510/20210425/microsoft-fixes-windows-10-bug-causes-stuttering-frame-rate-drops.htm)

**Comment by MuadDib90** [comment] 2021-05-06 16:18
> 
> 
> Safes should be easier to use after [24d04e8](https://github.com/Realm667/WolfenDoom/commit/24d04e8353777b70ef393016408a638d3dbe61e2).

A bit late, but finally got a chance to test it. It works very fine now, @AFADoomer 👍

**Comment by AFADoomer** [comment] 2021-05-13 17:39
I believe this can be closed.  Can anyone reproduce the invisible Hitler problem on current master?

**Comment by Tormentor667** [comment] 2021-05-13 17:41
I never had the problem before, no single time when testing the arena, so I have no idea how to reproduce it after all.

**Comment by Ozymandias81** [comment] 2021-05-13 18:01
I'll try to test this with C3 release, I think it is something related to pcs with bad performance on that particular spot, so maybe something goes wrong... Very vague anyway, will try this weekend hopefully (but using a cheat, not playing the whole C3M6).

**Comment by MuadDib90** [comment] 2021-05-14 06:14
I had only problems with Hitler do not appearing. This was due to stepping into the center, where he should appear, and your presence was a problem. But @Ozymandias81 solved this couple months ago by making invisible wall, so you can't step there.

But I personaly did not encounter "invisible" Hitler though... (like he IS there, but can't be observed).

**Comment by Tormentor667** [comment] 2021-05-14 09:59
Let's close this for now and wait for any beta-testing reports towards 3.1, right?

**Closed by Tormentor667** 2021-05-14 09:59 UTC
Labels: help wanted, playtesting, question

**Comment by Ozymandias81** [comment] 2021-05-14 18:53
I can confirm that I neither encountered any invisible Hitler, tested under C3 release.
