### ISSUE TITLE
Profile image not correct

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#377] opened 2021-02-14 14:08 UTC
Just before going to the mission C3M4, Sgt Ascher is saying something, but the image is still from Douglas.

![Screenshot_Doom_20210214_150320](https://user-images.githubusercontent.com/77861029/107878917-0cb24b00-6ed6-11eb-92b2-63c6d90dd8b8.png)

**Comment by Username-N00b-is-not-available** [comment] 2021-02-14 14:10
@x3003 Was it also Douglas before C3M3 and C3M2, or Ascher was replaced just before C3M4?

**Comment by MuadDib90** [comment] 2021-02-14 15:55
This was happening for me, if I went with the "debugging mode ON". Not in the normal play (meaning choosing the third episode and playing it as intended). Not knowing of any other cases, where this is happening...

**Comment by x3003** [comment] 2021-02-16 21:12
Dunno about the debugging mode, but I went from c1m1 to c3m3, just to play some maps.

**Comment by Username-N00b-is-not-available** [comment] 2021-02-17 06:16
@x3003 Did you just use ```map c3m3_a``` from the console? This explains things, I noticed this myself several times when testing :-D It never happens during normal play, though.
Maybe it's because after warping to another map via cheats the remembered intermap state vanishes, and when you return to the intermap, an OPEN script works instead of a RETURN one. Just speculating.

**Comment by x3003** [comment] 2021-02-17 16:11
Yes, just used changemap for that. No other cheats used ;)

**Comment by Tormentor667** [comment] 2021-02-18 18:39
This is certainly strange, there is no reason why this should happen after all.

**Comment by Username-N00b-is-not-available** [comment] 2021-02-18 19:16
@Tormentor667 I've tried to tackle this problem a bit, and now it seems to me that it happened because 1) second paragraph from [this](https://github.com/Realm667/WolfenDoom/issues/377#issuecomment-780330170), 2) some of the blocks in the ACS return script (```NPCDialogue```, the long one with a lot of ```if (mission_number ...)``` conditionals) check the mission number exactly (e. g. ```mission_number == 13```). When a player returns to the INTERMAP, the ```mission_number``` can already be set to something larger than 13, and that block of code will never run.
I think this current issue can just be fixed by adding ```ACS_NamedExecute("RETURN_INTERMAP", 0, false);``` to the end of ```ENTER_INTERMAP``` script and changing line 710 to ```if(mission_number>=13)```, but other unspotted problems with this logic can still be left somewhere.

**Closed** 2021-02-19 10:11 UTC
Labels: playtesting
