### ISSUE TITLE
Actor still following

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#502] opened 2021-04-21 21:55 UTC
In C1M2, ryan is still following when you don't want him to follow.

![Screenshot_Doom_20210421_223511](https://user-images.githubusercontent.com/77861029/115625636-9e866c00-a2fc-11eb-8a9e-9f0422f8e5fb.png)

Strangely there are places like this one were he doesn't follow, but usually he does.

![Screenshot_Doom_20210421_223620](https://user-images.githubusercontent.com/77861029/115625704-bcec6780-a2fc-11eb-9d4c-4c7c229ba77f.png)

Using the latest git version

**Comment by AFADoomer** [comment] 2021-04-21 22:03
Since the whole point of the level is to rescue Ryan, if you tell him to stay, then leave him too far behind, he will start to follow you anyway. 

If I remember correctly,  that second spot is scripted, because you're supposed to open the armory door.

**Comment by x3003** [comment] 2021-04-21 22:10
Well for example, there's the room were the 2 bosses come up from the tankyard and I rather don't have ryan dancing in front of me. But I can't even leave him 5 steps away from me.

**Comment by AFADoomer** [comment] 2021-04-22 03:37
Not sure what happened here, because I know this was working before...  But.  Should be working properly as of 41d7308ff95aa4e06a46f7fcee4e581d6365ea8f.

**Comment by Ozymandias81** [comment] 2021-04-22 17:13
Tested on C1M2 today, it works now (I am playing the old build before your commit and it had issues indeed, but tested again a while ago and it works as intended). So gonna close this.

**Closed** 2021-04-22 17:13 UTC
Labels: actor, gameplay, playtesting, suggestion
