### ISSUE TITLE
The final phase | Preparing the release

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#314] opened 2020-12-04 18:12 UTC
Dear friends,

we are nearing the release of **Blade of Agony**, what a journey! Now it is about time to talk about the approach for the final beta tests with a selected group of people and also about a release date and how to plan the marketing and the release party. This issue is just there for brainstorming about all that stuff right now and get a certain timeline and a certain plan for the time from now on until the release. Points we need to discuss are

- Release Date
- Trailers ([Teaser](https://youtu.be/sx7af6k_JCc) is released, Release Trailer in development)
- Advertisement on Gaming Portals (PCGamer, etc.)
- Website Updates
- YouTube Channel
- Social Media Viral Marketing

...and much more. Let me know what your thoughts are!

**Comment by DoomJedi** [comment] 2020-12-04 19:54
Well, you said trailer is in work...not sure what to discuss there, want to see the trailer and then we can discuss it.

Release date - have no opinion beside wanting it to be...as soon as it can be with proper testing and promotion. And sure after the trailer that is meant to promote it. At least a teaser we should have been posting yesterday, not tomorrow, we are already a bit too late on that IMHO.

I think we should send this version soon to Romero, having his post/feedback will help us to promote the mod.

I can sure promote the mod in my modding communities - Doom/Russian Doom community, Wolf3D, Keen. But better to have the trailer first. Showing russian translation screens can help me to promote it on russian forum.

PCGamer? Not sure how it works...we contact them, or they initiate contact...how was it last time? We need to promote it via youtube/twitch streamers, some can get an "Early Access".

**Comment by Tormentor667** [comment] 2020-12-05 14:43
The **teaser trailer** is done and I will post a news item on the _Blade of Agony Webseite, Realm667_ as well as the active communities (_Doomworld, ZDoom, ModDB, PCKF_, maybe you can take care of the _Wolf3D and russian doom community_ forums)

I'd also take care of sending the final version 2 weeks before the release to *John Romero* (as an selected early access, I will prepare an _e-mail_ for that)

Regarding _PCGamer_ and other *gaming sites*, I'd simply try to contact them, send a mail about the release and hope, that something is happening.

**Comment by Tormentor667** [comment] 2020-12-05 18:51
The teaser-trailer has been released: https://youtu.be/sx7af6k_JCc

**Comment by Ozymandias81** [comment] 2020-12-06 17:36
If I can I'll try contact [The Games Machine](https://www.thegamesmachine.it) and [I-Bitelloni](https://ibitelloni.com) italian blog once everything will be ready (I-Bitelloni did that [interview](https://ibitelloni.com/2019/06/04/blade-of-agony-intervista/) through me, remember?)

**Comment by madame-rachelle** [comment] 2020-12-07 13:10
I don't really have much of value to contribute to the thread, but I just wanted to say the trailer was amazing.

**Comment by Tormentor667** [comment] 2020-12-07 16:36
> 
> I don't really have much of value to contribute to the thread, but I just wanted to say the trailer was amazing.

Don't say that - at least you can still contribute your thoughts :)

**Comment by Talon1024** [comment] 2020-12-07 21:16
I sent an e-mail (through their web form) to GamingOnLinux.com, and they just [ran an article](https://www.gamingonlinux.com/2020/12/wolfenstein-blade-of-agony-chapter-3-gets-a-teaser-overhauled-chapter-1-2-coming) about this game. Thanks to @liamdawe for the press coverage!

**Comment by Tormentor667** [comment] 2020-12-13 11:32
Just uploaded a small video for Blade of Agony to our channel, it'll be online in about 25 minutes. It's mostly a comparison video between C1M1 from 2015 and C1M1 from 2020, and also explaining what we did to improve the mod and how it all began.

Link: https://youtu.be/6JmR1QuvbPI

Do you like it and do you think it's worth doing more of these? What content would you suggest? What things are worth being talked about? What can I improve?

**Comment by Username-N00b-is-not-available** [comment] 2020-12-13 17:10
@Tormentor667 I like this video format, such videos could work both as advertisements and as nice explanations for people who want to know more about Blade of Agony. They are definitely worth doing provided they do not take too much time and effort from fixing the remaining bugs :-)
As for the content, we can:

- show off advanced features which are exclusive to BoA or just really complex (e. g. disguise/stealth system, tanks, text papers and localization via a spreadsheet) and explain how they were done, and also give ideas on their further expansion in mods or in unrelated projects;

- pay attention to the process of making 'resources' (building complex structures in UDMF maps, making/converting models, drawing sprites, textures (+materials), and fonts) and sharing useful tricks which help to raise quality and reduce worktime;

- organize some Q&A with selected members of our team if they wish to say something special.

It would probably not be a good idea at all to talk about the plot, it's better to avoid it (a fraction of players could lose the point in playing the game).

On @DoomJedi's suggestion about John Romero, what about writing to other 'old-id' members, especially John Carmack and Tom Hall, who also have worked both on Wolfenstein and Doom?

BTW was the movement because of 2016?

**Comment by Tormentor667** [comment] 2020-12-14 17:17
Very valueable input @Username-N00b-is-not-available - this is great stuff, I will take care of that :) And no, the movement was not because of 2016 but due to the missing text explanations and a bad cut in the middle of the video.

**Comment by Tormentor667** [comment] 2020-12-17 15:53
Did another one today, more to come the next weeks :) 
Link: https://youtu.be/eIWqJXs3hjM

**Comment by Username-N00b-is-not-available** [comment] 2021-02-02 16:32
@Tormentor667 Around a week ago I sent you an email tangentially related to this, have you seen it yet?

**Comment by Tormentor667** [comment] 2021-02-02 17:45
Ugh... I didn’t get it - can you resend it please?

**Comment by Username-N00b-is-not-available** [comment] 2021-02-02 18:36
@Tormentor667 Resent it just now. Honestly, it is _very_ tangentially related :-)

**Comment by Tormentor667** [comment] 2021-02-02 19:59
Super strange, still didn't get it. Did you send it to info@realm667.com?

**Comment by Tormentor667** [comment] 2021-02-02 20:10
After taking a look at the things that are left to be done, I would suggest a final release date now for "Blade of Agony" - The 30th of April 2021 (fun fact: Hitler died on 30th of April as well). Do you think we can make it until then to prepare the final release and everything that's necessary?

@Username-N00b-is-not-available @Talon1024 @madame-rachelle @DoomJedi @doomjuan @Ozymandias81 @AFADoomer

**Comment by Username-N00b-is-not-available** [comment] 2021-02-03 08:20
If you ask me,
![We_Can_Do_It!](https://user-images.githubusercontent.com/59409713/106716779-e657fa00-660f-11eb-94a8-333f69694ee6.jpg)
To me it seems that almost 3 months would be enough for dealing with the problems we still have unresolved, then retesting with a larger group of people, balancing and polishing the game one more time. Though I would rather not advise to state the date 'officially' right now, even a large studio can underestimate the time needed to finish a game (from recent history, see id/Zenimax who had to take another four months to complete Doom Eternal).

---
@Tormentor667 Yes, I sent it to exactly that email address. Maybe some filter is blocking it or marking as spam, I don't know...

**Comment by Tormentor667** [comment] 2021-02-03 17:08
The thing is: I guess we need a definite date to work towards to. Otherwise, the release will take another year and I think we need to avoid ending up fixing details of details of details - that will be frustrating. We need to earn the praise we deserve finally :)

Still didn't get the e-mail unfortunately. I added you to the whitelist right now, can you try it again one last time?

**Comment by Username-N00b-is-not-available** [comment] 2021-02-03 17:32
@Tormentor667 I think that setting 30 April 2021 as the final date for ourselves would be appropriate. Not too early to fix all of this, but also not too far away in the future. What do other team members think about it?

Changed the subject and re-sent the message for the third time.

**Comment by DoomJedi** [comment] 2021-02-03 19:36
As deadline is not much related to my/art tasks, at first preferred not to react....but maybe just a few words...

First, before the rest - if you told in a trailer "1st quarter of 2021" - make some update post. As we all know quarter ends in 31 of March. 

About the rest...I think making such a complicated mod - we can't ever release it bugfree, even commercial games aren't free of bugs. Depending on your attitude - you won't release it in 5 years...or on the contrary - can release it much faster, it's all about attitude towards "reports".
Some are serious bugs, but some are nitpicks barely anyone will notice, and nitpicks won't ever go away, new tester - new nitpicks, and you can't please them all - EVER. 
For one - there is too much ammo, for other - too little etc...not every report - is a forced change need.
You know what honest judge is - when both sides find him unfair :) Good mod - is too hard for some, and too easy for some - while fair for all the rest.
And the more people get involved in testing - those reports will keep coming (and farther people are from BoA - the more "false reports" will come of intended features).
One has to stay focused, with release in mind.

**Comment by Tormentor667** [comment] 2021-02-03 19:38
I totally agree with you here @DoomJedi

**Comment by DoomJedi** [comment] 2021-02-03 19:51
Well, thank you :) You know I released a mod or two in my life and led a team of modders myself for many years...
It's hard to...let the baby go, there is always something you can improve...you feel like Schindler at the end, "if only I....".
That's the hardest phase of the mod my friend. Hardest - deciding when to release, despite some "reports"  still coming in from time to time.
That lack of control once you release...fear. That perfection urge...
As I always say (since moment I really understood modding enough) - Flawless mods are mods that are never released, and mods that are released - are never Flawless.
I'd even say more - many - love to find and see those little imperfections, it adds to the charm. Really. It makes mod more real and relatable. Adds to the discovery.

You know, even commercial companies - later release patches and bugfixes, professional companies. Don't expect to do better with such scale of a project and number of people involved.

**Comment by Tormentor667** [comment] 2021-02-07 08:54
By the way, I got my hands on the first draft of the final trailer - looks awesome so far, currently just waiting for some fine-tuning before I will present it to you :)

**Comment by MuadDib90** [comment] 2021-02-09 11:47
> Dear friends,
> 
> we are nearing the release of **Blade of Agony**, what a journey! Now it is about time to talk about the approach for the final beta tests with a selected group of people and also about a release date and how to plan the marketing and the release party. This issue is just there for brainstorming about all that stuff right now and get a certain timeline and a certain plan for the time from now on until the release. Points we need to discuss are
>
>* Release Date
>
>* Trailers ([Teaser](https://youtu.be/sx7af6k_JCc) is released, Release Trailer in development)
> 
>* **Advertisement on Gaming Portals (PCGamer, etc.)**
>
>* Website Updates
> 
>* YouTube Channel
> 
>* Social Media Viral Marketing
> 
> 
> ...and much more. Let me know what your thoughts are!

@Tormentor667 Is it worth me trying to contact some of the Czech web pages reviewing games?
If so, what should I say? What is expected from me?

**Comment by Tormentor667** [comment] 2021-02-18 18:13
Yes, you can definitely go for that. If they are interested, we can give them a beta-access so can review them and preview them in a news item for the release date - what do you think?

**Comment by MuadDib90** [comment] 2021-02-18 19:12
Sounds good.
So I can offer them a beta access, if they agree to the terms releasing the review on 30 Apr at the earliest?
How much ahead of time I can tell them they can have the beta access, so they have time to review it? Two weaks?

**Comment by Tormentor667** [comment] 2021-02-18 20:05
They can have it right now, and they can post a preview before April 30th but not give too much detail :)

**Comment by MuadDib90** [comment] 2021-02-19 04:53
OK, I'll try to arrange that ;-)

**Comment by MuadDib90** [comment] 2021-02-28 17:37
> 
> 
> OK, I'll try to arrange that ;-)

For those, who don't know, the Czech (biggest I think) gaming magazine Score (www.score.cz) showed interest in making the review of BoA. - Still waitinig for message from others I wrote to though...

**Comment by Tormentor667** [comment] 2021-03-13 15:46
Just to make sure that everyone gets the notice, I wrote an email to John Romero 2 days ago:

> Dear John,
> 
> it's been a while since our last contact which I think was around 2017 - 4 years, time is running, especially
> when you reconsider what has happened to anyone of us in the past 12 months. Well, but this mail is not
> about the bad and the ugly, it's about things that still keep us entertained, that keep us motivated and
> that keep us creative.
> 
> In the past 4 years, the team and I dedicated a lot of effort towards the final release of our project
> "Blade of Agony". We filled up the webpage with new information and content, we worked hard on the
> overhaul of Chapters 1 and 2, and we finished the final Chapter 3 of our mod which became
> a "standalone" game in the meantime, but still based on our favorite 3rd person shooter - Doom.
> 
> At the moment, we are doing final touches, we have released a teaser trailer and we are thoroughly
> testing the game from the beginning to the start and preparing the release that is planned for April
> 30th in 2021 - not far from now, considering the long development time of over 6 years.
> 
> So, why am I writing this email to you?
> You, dear Mr. John Romero, are what we consider to be the rockstar among the game developers
> of our youth, responsible for the 3d games that didn't only have the biggest impact to the industry
> in the 90s but also for us. Without id software, there wouldn't be Blade of Agony - and not hundreds
> of hours of entertainment for us, developing the game and making it available for free to hundred
> thousands of gamers (we had quite an overwhelming impact with "BoA" as well :)).
> 
> Let's get to the point: We'd be honored if you take a look at our release candidate that I have uploaded
> for you, and we'd be happy to know what you think about it, what you like, what you do not like and
> if there are any words you'd like to share with us.
> 
> Download: https://www.mediafire.com/file/o3k97a4plyreswg/boa_rc1_20210309.zip/file
> 
> Your Twitter post 4 years ago was an amazing moment for us, to see, that the developer of Doom himself
> noticed our work - and actually liked, what we did. A great motivation boost and some special kind achievement
> for every single person from the team. Thank you for that. And we really hope - if you have some time left
> (the game takes about 20 hours from the beginning to the end, about 7 hours for the all new Chapter 3) -
> that you can enjoy the game, and maybe feel a good mix of nostalgy and pride, seeing, what your vision
> and your effort has prepared almost 30 years later.
> 
> Thanks for reading, stay well, and greetings from Germany, Italy, Britain, Israel, Russia and the U.S.!
> 
> Mit freundlichen Grüßen | Best regards
> Daniel Gimmer 
> Tormentor667

I added inline links to the mail which are not visible here, pointing him towards a download and our webpage.

**Comment by xSonicB00Mx** [comment] 2021-03-14 13:17
Hey Daniel! I am just hanging out in your GitHub anticipating the release. I just wanted to inform you, that your e-mail above contains a visible link to the release candidate. I don't think it was intended to go public? Anyway, good luck with the final stretch until the official release!

**Comment by Tormentor667** [comment] 2021-03-14 15:20
Thanks kindly, just updated the post :)

**Comment by Tormentor667** [comment] 2021-03-24 21:20
Only 5 weeks left until the release - we need to speed up fixing our issues friends.

How are your schedules @Username-N00b-is-not-available @Ozymandias81 @doomjuan @AFADoomer @DoomJedi @MuadDib90 @Talon1024 ?

**Comment by AFADoomer** [comment] 2021-03-24 23:51
My schedule is crap, but if you assign specific things to me, I'll work them.

**Comment by Username-N00b-is-not-available** [comment] 2021-03-25 07:32
@Tormentor667 I have very little time now, so my participation will sadly be limited to updating language.csv when needed (and commenting on issues here if I happen to know something)...

**Comment by Ozymandias81** [comment] 2021-03-25 15:58
I'll try to do what I can, you know how are things for me unfortunately lately

**Comment by MuadDib90** [comment] 2021-03-28 07:05
I am working on language.csv overhaul. As for now current points for discussion are in the issue thread. Remaining sections go through for me are _text papers_; _dev coms_; _secret messages_ and _info&help texts_.

But I think I can manage to finish it, and still let you have some time for repairs, if necessary.

**Comment by Tormentor667** [comment] 2021-03-28 07:46
Very good!

**Comment by MuadDib90** [comment] 2021-03-29 14:28
> 
> 
> > OK, I'll try to arrange that ;-)
> 
> For those, who don't know, the Czech (biggest I think) gaming magazine Score ([www.score.cz](http://www.score.cz)) showed interest in making the review of BoA. - Still waitinig for message from others I wrote to though...

![01](https://user-images.githubusercontent.com/73436978/112846753-ab6dc200-90a6-11eb-9567-4458060bbaba.jpeg)

The good news is the review from Score is compelete. The bad news is noone else I wrote to replied back; and I guess they won't anymore. Never mind though...

New number of the Score magazine will be released in 9.4., so then we will see the final result.
All I can say now (judging by the word spoken) is they have been quite surprised by the level od professionalism and sense for detail(s). 

I'll be back (no pun intended) with translating the review after the release. I won't let you miss it, guys!

![mic](https://user-images.githubusercontent.com/73436978/112851943-bd059880-90ab-11eb-96f9-872124f2012d.PNG)

**Comment by Tormentor667** [comment] 2021-03-29 20:02
Can’t wait to read it in English :) Is it a print magazine?

**Comment by MuadDib90** [comment] 2021-03-30 03:50
> 
> 
> Can’t wait to read it in English :) Is it a print magazine?

Yes, it is a print magazine. :)

**Comment by Tormentor667** [comment] 2021-03-31 19:13
I just sent E-Mails to 16 of the big pc games magazines and pages, pointing towards our game. Let's see what it's worth for :)

**Comment by MuadDib90** [comment] 2021-04-09 14:26
Dear fellow developers,

since today the review from magazine Score came out (and all subscribers should have it by today I guess; so they can loot their PO boxes), I can finally present the material that has been sent to me. (Btw I ordered a hard copy, naturally :D )

Many gamers still have to wait for BoA proper release, but on the other hand THIS is the moment the developers are waiting for.
(I am making it unnecessarily 'Torment and Torture', am I? :D:D Sorry, couldn't resist.)

Well, it is not word by word, but I tried my best to convey the idea behind it.

So, without any further delays here is the review from Czech gaming magazine with outreach all over Czech Republic and Slovakia:

<details>
  <summary>Two pages review:</summary>

![00](https://user-images.githubusercontent.com/73436978/114193468-d978bf00-994e-11eb-92b7-c5ead1ade8d6.png)
</details>

**WOLFENDOOM: BLADE OF AGONY**

Developer: realm667 // Publisher: Standalone mod // Multiplayer: no // Czech: in preparation //
Recommended age: 18+ // Price: free

It was a year 1992. Prague together with Bratislava belonged to the same republic. Right in January, the 1st public Czech TV station was established. In the last day of the same year (31.12.) the Czechoslovakia was divided. Prague and Bratislava became ambassadors of their own country. But before that, on holidays in the middle of the year, 30th of July, Václav Havel abdicated the post of a president (translation note: former president of Czech and Slovak Federative Republic and later, from 1993-2003, the first president of Czech republic). He was maybe exhausted by playing Wolf3D, which came out in 5th of May.

The year passes by, with the rock star as the Wolf all the faster, and 10th of December 1993 "the DOOM" comes out. One of the most influential FPS of all time, and for many gamers untouchable treasure. Both games are from ID software. Wolf plays the second violin from now on. All the more iconic status is attributed to him. It is nearly three decades now, when both plays were introduced. Theatrical stage creaks and scenes are scuffed. Pull the curtain and take a break. Because now, after 28, respectively 29 years, the Second Act is coming. And it will be spectacular. 

KEIN ROCK 'N' ROLL! ABER WOLF 'N' DOOM!

The Blade of Agony was released already three years ago. The grand mix of two games mentioned above. The mod on GZDoom port brings B.J.Blazskowicz in hell. The Polish-American killer of the Nazis is back. He may be quite shocked, many things has changed since his last duty; not much is left from his bygone adventures. The time spent in retirement has signed on him. Fortunatelly, he had more than able substitute, and the road was paved by the Doomguy himself. The foot-mark is quite significant. Where this colossus steps, grass do not grow for a week. Even the first few steps will have you know, where exactly this paved road leads. Opening intermezzo, where B.J. is asked for coming back to duty by his friend, cpt. Douglas Blake, is already an exceptional event. After two minutes of playing, we got a feel at the back of our heads, that someting big is awaiting us. The Act in retro costumes, in renovated theatre. It's bigger, with better acoustics and the entry is voluntary; no one is at the box office.

BoA is a homage to all FPSs of 90's. The shooting however comes side by side with a story. Back then the stories were not so important, shooting was the main focus. In BoA you can have a talk with friends from the front in the mess hall before mission, buy an armor and mine detector in the armory, then go to briefing room. Here you can enjoy the dias and you will be familiar with the mission. The last thing which remains is to hop on the jeep and go behind enemy lines. Our fingers itch already.

_Pic.01 - "Ja fol her dochtor." I bet you won't throw a syringe at us..._
_Pic.02 - A calm and nice sunset in a bunker with explosives. With no smoking signs of course._
_Pic.03 - Wolfendoom knows even a stealth mod. Soon, we will cut throats to all those brass._
_Pic.04 - We would swear, we're seeing the Hell Imp to fall down!_

It can't be denied that shooting is the prim here. Because the curriculum is written in old Doom engine, noone can be satisfied with only the average. Shooting has to have the balls. Ladies will forgive. When you grab the shotgun, you want to feel its power, its sanctity. You want to feel appropriate emotional response after the first shot. This all is here. The shotgun is powerful, as we all want it to be; and then we said: hell, that's sharp. And two Jerries went down after the first "bam". Tempo is so fast, as we all know it from Doom. We are experiencing an ecstasy and continue on. Fully in the atmosphere of 92'.

Each mission is different. Not every time it is necessary to kill all that moves. And when you rescue cpt. James Ryan, he will join you in the next mission and you both will be killing Nazis side by side. Whereas in the first mission of second episode the stealth mechanics comes in. Its simplicity is high, but as a rest from shooting it's good enough. It's something you just wouldn't expect from this kind of a game; the more we liked those parts. Health on minimum, health packs are not on demand and we are changing the approach. Mindless shooting is putted aside to more careful progression through the shadows. The game responses to the light, where you are detected. Nothing complicated. After you kill all the enemies coming at you, when discovered, the alarm goes off and you are again "invisible".

Missions reflect even the time period they are in. Thus you will visit beaches of Normandy, where you will be blowing up the artilleries, while Allies will try to get through the beach. First locations are situated in Tunis, another time you're running through the bunker. This is the beauty of each environment. They are so visualy variable the boredom never comes by. Interiors are interwoven with details. No plain poor walls. Pictures, signs, not excluding banners with swastika. When you walk in to the officer's office, it looks like in the officer's office. The picture with Führer is not missing. The exteriors are maybe even better. Trenches, falling snow or night mission. Everything is precise, at the limit of the engine; all that is grandiloquent, without exaggeration at all.

Now, we will admit our small bias. When we were installing the mod, we expected a few hours of gameplay, built on although solid, but rather old foundations. But we got first two episodes completely redesigned (those who played before will appreciate it, others don't have to care), and finally the new third episode. Contrition from our side is right here. The gameplay time is at today's standards unseen, and be it a free mod, this counts two times. We were amazed after beating ten hours of gameplay, what all the developers managed to do, and even the fact the game wasn't boring at all after all that time. Majority is driven by delightful maps with all that shooting. The shotgun was mentioned, but not any other weapon, not even pistols, are behind. So, that what we wrote to minuses of the game consider as a maximal nitpicking we are capable of.

With this we can close our Ode to Joy. Did you ever think, how the Wolf from WWII in the hellish world of Doom would look like? This is your answer. With professional approach, modern gadgets, and still with the spirit of 90'. Instead of reading other recommendations, you'll do the best when you download this and experience this mix for yourself. Send developers some money, they damn deserve it. Also czech subtitles are in preparation, which weren't available at the time of review. It was a hell of a ride. And as we have indelible memories of Doom and Wolf3D, we will be remembering Wolfendoom in a few years with the same feeling!


**3x WHY AND NOT OTERWISE**
_SHOTGUN_
All the weapon arsenal is fine, but once you got your hands on shotgun, you're somebody else. In that moment from BJ is Doomguy and tremble all the living.

_STEALTH_
We certainly didn't expect this. Crawl through corners and silently cut throaths of Nazis to destroy the radio stations, it caught us by surprise. The mechanic also works pretty well.

_BLOWING UP THE TANK_
The shotgun is powerful, but for the tank you need another caliber. Rockets, for the best. Load, aim and shoot. Then hurry to the trench.


**WE LOVE**
Treasure. In the old Wolf you could find treasure everywhere. BoA is full of similar stuff. You can even buy something useful for these goodies. Appropriate usage of Nazi's treasure.

**LOVE SQUARED**
Voices. The talks are maybe quiet, but when the Jerries are rushing at you and start to shout their commands, shooting the Nazis were never better.


**VERICT**
_PLUS_ -- perfect mix of FPS from ID software, story, sounds, level of details, tempo, maps, shooting 
_MINUS_ -- from time to time annoying wandering
= -- Extremely brilliant honor to Wolf and Doom. It is not only the "addition" from fans, but rather a full-game in a professional design. With an addition of a story, it is nearly criminal to release this mod as free.

**DIFFICULTY**
old good Doom - 5 levels

**GAME LENGTH**
10-15 h

**PLAYED**
13 h

**OVERALL == 92 %**

**Comment by Wolfenburger** [comment] 2021-04-09 14:29
Will testers be in the credits? Hate to sound like a selfish prick but idk would be kinda cool to see all testers in the credits.

**Comment by Wolfenburger** [comment] 2021-04-09 14:56
> Will testers be in the credits? Hate to sound like a selfish prick but idk would be kinda cool to see all testers in the credits.
> 
> > I just need to [add you on the lines](https://github.com/Realm667/WolfenDoom/blob/master/wolf_boa_cr.txt#L517), yes... But we usually include playtesters who have definitely contributed to the mod somehow, and you will be in. --Ozy81

I hope I've contributed. I've found a few more bugs I'll report tomorrow.

**Comment by DoomJedi** [comment] 2021-04-09 17:51
Wow, simply wow...

Can I post it on russian forum?

**Comment by Wolfenburger** [comment] 2021-04-09 18:37
> Wow, simply wow...
> 
> Can I post it on russian forum?



> Wow, simply wow...
> 
> Can I post it on russian forum?

Post what?

**Comment by Talon1024** [comment] 2021-04-09 18:38
> > Wow, simply wow...
> > Can I post it on russian forum?
> 
> > Wow, simply wow...
> > Can I post it on russian forum?
> 
> Post what?

The review from the Czech magazine, of course.

**Comment by Wolfenburger** [comment] 2021-04-09 18:39
> > > Wow, simply wow...
> > > Can I post it on russian forum?
> > 
> > 
> > Post what?
> 
> The review from the Czech magazine, of course.

Oh that. That'd be epic. I wonder if game informer is still around. Would be crazy if we landed on there.

**Comment by MuadDib90** [comment] 2021-04-09 20:44
> 
> 
> Wow, simply wow...
> 
> Can I post it on russian forum?

Sure, @DoomJedi.

**Comment by Tormentor667** [comment] 2021-04-11 15:36
I just posted the article on our webpage.

**Comment by Tormentor667** [comment] 2021-04-12 12:42
**Release Trailer has been published**
https://www.youtube.com/watch?v=VV6VjlgAA5s

It has been posted to
- Doomworld
- ZDoom
- PCKF
- ModDB
- Blade of Agony Page
- Facebook (various groups)

Feel free to share it as well :)

**Comment by DoomJedi** [comment] 2021-04-12 12:43
Also on Russian Doom forum, 
Team Raycast Forum
....

**Comment by Talon1024** [comment] 2021-04-12 15:02
I just tried to send an e-mail to GamingOnLinux.com (via the contact form) about the trailer and the Score magazine review.

**Comment by Talon1024** [comment] 2021-04-12 17:14
The [article on GamingOnLinux.com](https://www.gamingonlinux.com/2021/04/wolfenstein-blade-of-agony-releases-chapter-3-plus-a-revamped-chapter-1-a-2-on-april-30) is now up! Thanks again to @LiamDawe for the press coverage.

**Comment by Tormentor667** [comment] 2021-04-12 18:42
Awesome!

**Comment by DoomJedi** [comment] 2021-04-12 19:12
We are on moddb front page, was glad to help :)

**Comment by Tormentor667** [comment] 2021-04-12 19:16
> We are on moddb front page, was glad to help :)

Wohoo :)

**Comment by DoomJedi** [comment] 2021-04-12 19:36
Russian youtuber (2500 subscribers):

"Thank you!

Okay, the video will be out after the 30th. I will try to release it on May 1st. Thanks for the translations, since the Russian language is there, then of course I'll try with it. :) As for the rest, I will work on it. I will notify you as the video comes out and send you a link"

**Comment by Tormentor667** [comment] 2021-04-12 19:53
Awesome!

**Comment by DoomJedi** [comment] 2021-04-12 20:02
I follow some retro gaming russian youtube channels of 300K, 450K+ subscribers, I wonder if I can try convincing any of them to make a video. That would be a hard task though, guys like that are quite a celebrity among retro gamers and our mod is not exactly their review profile...

**Comment by Tormentor667** [comment] 2021-04-13 18:49
That would be awesome if we can make it!

**Comment by DoomJedi** [comment] 2021-04-16 19:23
Guys, I want to voice my subjective opinion about what's going on now, 2 weeks before release.
The opinion is subjective and I just want to voice it, do something with it or do not - I won't comment any further and you won't change my subjective mind about it.

2 weeks prior to release is the time to focus on important stuff and report, big, critical bug report, glitches.

This is NOT a time at all for:

1. Fixing ton of nitpicks noone will notice unless they do A than B than 2 times C and then 6 times D with 1 second delay.
This while larger stuff await treatment. Such hard to recreate reports should be ignored completely, and not take most of your time - as it seems currently.

2. Changing map (well tested and balanced and re-balanced previously by MANY) due to 1 single report of some Boss being too easy or too hard.  This is absurd, really absurd. Especially as BoA has damn skill levels. 
We are not to please anyone in particular and sure not all, so one single report about ANYTHING of this matter, sure difficulty (subjective anyway) - should be ignored.

Guys, you need a HUGE filter on reports at this point. Those are not regular times, it's 2 weeks before release!

when larger stuff are

**Comment by Tormentor667** [comment] 2021-04-17 06:57
I totally agree here and I am sure the rest of the team does as well. Thanks for hinting us, and time to concentrate and focus on the aspects we really need to take care of! Let's bring this to an end :)

**Comment by DoomJedi** [comment] 2021-04-17 07:08
Thank you and you can always count on me to speak out, regardless of being a popular vote or not, sharing my personal thoughts and subjective modding conclusions.
All put of care for this project and release

**Comment by Tormentor667** [comment] 2021-04-25 19:19
Any suggestions regarding promotion for the 30th?

**Comment by DoomJedi** [comment] 2021-04-25 19:56
We could release nude calendar of team members....

...now seriously.

What about live stream of developers, answering questions etc? We can even make live studio that will comment like news podcast on events during the release day, like number of per hour downloads etc :)

Giftaway for 100s downloader?

**Comment by DoomJedi** [comment] 2021-04-25 20:00
Maybe all with try to get attention of the MOST hyped youtuber in retro gaming of his language/country? If you send to many ,some might agree....

**Comment by madame-rachelle** [comment] 2021-04-26 00:06
> 
> 
> We could release nude calendar of team members....
> 

Only the core team members right? I did not ever agree to this! 😆🤣

**Comment by MuadDib90** [comment] 2021-04-26 17:12
> 
> 
> Maybe all with try to get attention of the MOST hyped youtuber in retro gaming of his language/country? If you send to many ,some might agree....

Speaking of "retro", how about to try to get in touch with RETRO REPLAY [https://www.youtube.com/channel/UCx42AsHSKnjEfPXk0YiGCyw](url) to think something up?
Although they play console games the most, and then there is that big question mark IF they would be even willing! So mad, it didn't pop up in my mind earlier though...

**Comment by Tormentor667** [comment] 2021-04-28 20:58
Regarding the release day, I‘d suggest using the latest possible and available time on the 30th of April so we can bugfix and test as long as possible.

I am currently testing 4-5 maps per day, even testing around during my mid day breaks, and a lot looks really good and ready to be released. Thanks also to all the other testers currently around.

Still it’s scary how many things are breaking lately.

**Comment by Tormentor667** [comment] 2021-04-29 07:06
Concerning the release: I will compile the final version in about 33 hours from now.

**Comment by Ozymandias81** [comment] 2021-04-29 09:34
Remember that the ipk3 must not have any kind of compression methods applied, so that will save memory. And better release the mod even around midnight of 30th April, I did the same for BlooM Demo (but well also for a different reason too, it was Halloween)

**Comment by Tormentor667** [comment] 2021-04-29 10:45
All fine, we will squeeze out every single minute for bugfixing that we have ;)

**Comment by Ozymandias81** [comment] 2021-05-12 20:34
C3 has been released, and now we plan to release 3.1 at least when a stable build of gzdoom will be out. I'll close this, feel free to reopen if you need it for something else.

**Closed by Ozymandias81** 2021-05-12 20:34 UTC
Labels: actor, discussion, help wanted, playtesting

**Comment by mcphail** [comment] 2021-05-28 23:41
I made a little visualisation of the path to 3.0 using `gource`. I don't think I can embed videos in github comments, but you can download [here](https://mcphail.uk/boagource).

**Comment by Tormentor667** [comment] 2021-05-29 08:39
Cool ;)

**Comment by Talon1024** [comment] 2021-05-29 08:48
It is actually possible, using drag & drop. See my comment on #592
