### ISSUE TITLE
[3.1] Keen Levels: BJ's current health is reset to 100% upon death or level exit. Also loses the majority of his inventory.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#679] opened 2021-05-21 19:48 UTC
If BJ's current health is over 100% when the player starts a Keen level, his health will be reset to 100% by the time he "returns" to Allied HQ, though he can be healed by Bones to whatever his current maximum health is.

**Comment by Shockwave508** [comment] 2021-05-27 11:45
Upon further inspection during my Episode 2 playthrough, this glitch also removes whatever armor BJ was wearing.

**Comment by AFADoomer** [comment] 2021-05-30 01:44
Can anyone else reproduce this?  The problem isn't in the morph actor; both the tank and Billy have the same code to handle setting armor and health back to the original pre-morph values.

**Comment by Tormentor667** [comment] 2021-05-30 10:24
Before Keenmap:
![grafik](https://user-images.githubusercontent.com/10298439/120100601-db3a5400-c141-11eb-83d0-90ec823bedc2.png)

After Keenmap:
![grafik](https://user-images.githubusercontent.com/10298439/120100628-fefd9a00-c141-11eb-8f0e-9d80b2118a8e.png)

The amor is gone, the health is still there.

**Comment by AFADoomer** [comment] 2021-05-30 19:09
This should be resolved as of 6307aed04a744b17ba60592d47983e3010975d0f.

**Comment by Tormentor667** [comment] 2021-05-30 19:14
Sorry, didn’t try it yet so can’t confirm but will check later.

**Comment by Shockwave508** [comment] 2021-05-30 22:29
Can confirm that it works, but BJ still mysteriously runs out of stamina when exiting a Keen level.

**Comment by Shockwave508** [comment] 2021-05-31 02:32
Upon further testing, from a "low-health" state at 19%, BJ's current health is still reset to 100%, and the low-health audiovisual effects are still being seen and heard. You also lose all your accumulated Gold upon returning from a Keen level.

**Comment by AFADoomer** [comment] 2021-06-03 23:47
I think that the problem here occurs if you die (or otherwise save/reload) while you are playing as Keen.  Because this is a player morph, your inventory is reset.

**Comment by AFADoomer** [comment] 2021-06-04 01:48
I think that d575b05187498f79fdd985edf703916a2f0ffce0 fixes this, but please test.

**Comment by Shockwave508** [comment] 2021-06-04 19:59
The script only works the first time you launch a Keen level, die, then return to HQ. If you do this cycle a second time, you still lose everything.

**Comment by AFADoomer** [comment] 2021-06-05 15:48
OK, should be good after d7c244a3ad322418ceafc6312b64f5c7dd4a9de3.

**Comment by Shockwave508** [comment] 2021-06-05 16:13
First run of a Keen level: Health is reset to 100%, but everything else stays, even Armor.
Second run/death in a Keen level. Health is reset to 100%, Armor stays, all Inventory items are lost, even the Keen Cartridge you were using.

**Comment by AFADoomer** [comment] 2021-06-05 16:21
OK, so the health is a problem...  Again.  *sigh*

But I just entered a Keen map, killed myself by jumping into tar, respawned in the lab, and repeated 5-6 times, and my inventory was restored each time.  

Are you restoring from save at any point in your testing?

**Comment by Shockwave508** [comment] 2021-06-05 16:27
Will start a fresh Episode 1 run. and get back to you on that.

**Comment by Shockwave508** [comment] 2021-06-05 17:51
Can confirm that armor and inventory items are being restored after two or more Keen Level deaths. BJ's current health is still reset to 100%, no matter how high or low his health was when he plugged in the Keen Cartridge.

**Comment by Tormentor667** [comment] 2021-06-05 18:04
Is this really a problem considering that you can maximize your health in the hq?

**Comment by Username-N00b-is-not-available** [comment] 2021-06-10 11:31
@Tormentor667 Is it possible to add a crutch here in some sort of REOPEN/ENTER script that would check if the player is spawned near the SNES (just the coordinates with say 32.0 map unit tolerance) and apply healing effects (e. g. just [HealThing](https://zdoom.org/wiki/HealThing)) to the player pawn if so?

**Comment by AFADoomer** [comment] 2021-06-10 14:05
No need, there's already a code block that gets run after returning from Keen maps.

I was thinking of expanding the InventoryHolder class to also save health and armor as a fix for this.

**Comment by AFADoomer** [comment] 2021-06-11 02:07
OK, should be fixed after a96b408e229f5b791634e06dd12efcf6524a0f4e.

**Comment by Shockwave508** [comment] 2021-06-11 19:58
Health is now restored properly, yet the player's current armor class isn't saved/restored.

My Flak Jacket got "converted" into that 0% protection Heavy Combat Vest, upon recent testing.

**Comment by AFADoomer** [comment] 2021-06-11 20:17
That makes no sense. Health and armor values and save percent are saved/restored within a couple of lines of each other in the code.  And this was working for me (though I was just giving myself a single armorbonus item) - the code I was using to print the save percent on the inventory icon is still commented out in the status bar code.

 I'll test again tonight...

**Comment by AFADoomer** [comment] 2021-06-13 02:42
I think that this should be resolved after @Talon1024's commit at 744cefdadced9dfafd1664b4047f1516e05c4475.

**Comment by Shockwave508** [comment] 2021-06-21 17:25
Have to open this up one more time.

Dying, exiting, and re-entering a Keen level several times in a row will strip the player of his armor and inventory items.

**Comment by Tormentor667** [comment] 2021-06-21 18:52
Not again :D

**Comment by Username-N00b-is-not-available** [comment] 2021-06-21 20:00
An inventory problem also happens to C3M0_B...

**Comment by AFADoomer** [comment] 2021-06-22 01:26
It's better now...  It only happens if he dies and you replay the SM map, *then* die again and go back to the main game. 

🙄

**Comment by AFADoomer** [comment] 2021-06-24 01:21
I think this is fixed after d02c7b3203876e8635a980fe65839ef67a0ff380.  I force the game to autosave whenever the Keen player spawns in.

Fun quirk of Doom level exit functions...  You can't exit a level while dead via most normal methods, so have to be respawned in order to exit properly.

Fun quirk of Doom respawning:  If you are in a hub/cluster and respawn and there's no 'current' save file,  G_InitNew, called via DoReborn function, clears all hub progress.

So forcing a respawn in order to allow a return to the overworld was clearing the hub state and losing all INTERMAP progress/changes.

Or at least, that's what I think was happening.  :sigh:

**Comment by Username-N00b-is-not-available** [comment] 2021-06-24 08:43
But there is also ```disableautosave 1```, I think a significant portion of players uses it, maybe some percent...
@AFADoomer To force level exit from ACS, it is possible to set the script's activator to world before calling the exit special: ```SetActivator(0, AAPTR_NULL);``` (as it was in my original no-menu crutched implementation). Could it help here to avoid respawning on the Keen level? ForgetState is already in MAPINFO, by the way.

**Comment by AFADoomer** [comment] 2021-06-24 11:04
Calling the save function from ZScript ignores the disableautosave CVar.

This should be working as intended now...

**Comment by Username-N00b-is-not-available** [comment] 2021-06-24 11:36
@AFADoomer I checked it right now on new commit, and the armor does not get restored after second CK visit:
start a new game in C1, then prepare the player for testing with ```give cartridge51; give boacompass; give grenadepickup 4; give mp40; give ammo9mm 5; take health 27; give supershield; summon tntbarrel2; mdk``` (you can Ctrl+V this into console). Use the SNES and make the player die, return to Shadowlands. All inventory seems intact. Use the SNES once again, let the player die, then once again return to INTERMAP. The player has no armor anymore...
Not sure about the armor being the only problem for now.
***
Related:
![image](https://user-images.githubusercontent.com/59409713/123256307-7e8c4800-d4f9-11eb-93cb-56c5ed695597.png)
Should I just make the text shorter, so it is drawn on two lines instead of three?

**Comment by AFADoomer** [comment] 2021-06-25 03:27
The menu entry problem should be fixed in 9f2ed9eb1682c6606dc093ec38ce5f818a22a615.

**Comment by AFADoomer** [comment] 2021-06-25 04:06
And I think the armor save issue is fixed after b7e9adea6e0434a4c2746a6386930541e07c9ac0.

**Comment by Username-N00b-is-not-available** [comment] 2021-06-25 08:57
Yes, seems to be fixed! Finally. Also works with Ryan.

**Closed by Username-N00b-is-not-available** 2021-06-25 08:57 UTC
Labels: playtesting, resources

**Comment by Tormentor667** [comment] 2021-06-25 18:51
Finally :D
