### ISSUE TITLE
Some dead tanks can still trample

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#319] opened 2020-12-12 08:43 UTC
![deadtanktrample](https://user-images.githubusercontent.com/6550500/101979580-2f9d5600-3c2c-11eb-89cd-3c6934ab2929.gif)

**Comment by Ozymandias81** [comment] 2020-12-12 10:46
This means that some treads related "hitbox" actors doesn't disappear before DoDeath effect or something like that, and I also see that it is happening on a sloped surface... We also need a variable that allows us to make disappear the destroyed body after a while, for example defining it as a user variable so to avoid dead bodies to block passage on narrow zones, that's also up to mappers to set them that way or not. Any ideas @AFADoomer ? I might check it tomorrow maybe

**Comment by AFADoomer** [comment] 2020-12-13 00:37
Should be fixed in 99a24d74ef7b5fcda9a4d50f173a55ac5c801b00...  I *think* this was caused by the dead tank sitting on a slope, so still having velocity internally, even though it looked like it wasn't moving.

**Closed** 2020-12-13 08:32 UTC
Labels: actor, bug, playtesting
