### ISSUE TITLE
[CaptainJ] Infighting enemies not killing each other

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#1190] opened 2022-02-14 13:40 UTC
At the first level of Astrostein, Templars and Nazis really don't hurt each other despite they're throwing grenades around. Well in Episode 1 they killed each other. Should i turn off the god mode or something?

![grafik](https://user-images.githubusercontent.com/10298439/153874823-802b347b-1d12-4dc7-b99d-5197fca9a978.png)

**Comment by Username-N00b-is-not-available** [comment] 2023-04-19 08:45
Can't reproduce this with godmode, the Templars easily kill the guards and have no problem damaging the Übersoldat. This is likely to have been fixed in an earlier commit.

**Closed by Username-N00b-is-not-available** 2023-04-19 08:45 UTC
Labels: playtesting, actor, gameplay
