### ISSUE TITLE
[C3M3_A/B] Orientation of flak fire into the sky wrong

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#211] opened 2020-07-19 15:07 UTC
![2020-07-19_170646](https://user-images.githubusercontent.com/10298439/87878074-4f648100-c9e2-11ea-97a6-e3e9babaade0.jpg)
Noticed that the angle/roll/orientation of the flak fire in the sky isn't correct anymore.

**Comment by Ozymandias81** [comment] 2020-07-19 16:45
Earth and Moon as well with shaded effects over both things doens't have correct placement on C2M0_B, also there seems to be problems with lasers inside New Berlin (but everything works fine near MechaHtiler zone)
![Screenshot_Doom_20200719_184250](https://user-images.githubusercontent.com/11136108/87880200-00254d00-c9f0-11ea-8597-2a2e4bef4959.png)
![Screenshot_Doom_20200719_184400](https://user-images.githubusercontent.com/11136108/87880203-03b8d400-c9f0-11ea-93b1-aa114bd0d8b5.png)

**Comment by Ozymandias81** [comment] 2020-07-19 17:02
The problem mentioned by Torm I guess it is related to new tracers, just tested under 4.4.2 and I see same issues (even on c2m0_b, but that's something different I think)

**Comment by Ozymandias81** [comment] 2020-07-19 17:21
Regarding earth and moon, if I replace SceneryBase with Actor on ModelBase class, they works as intended again:
![Screenshot_Doom_20200719_191901](https://user-images.githubusercontent.com/11136108/87880797-f94d0900-c9f4-11ea-93e2-28f1c36eaf36.png)
![Screenshot_Doom_20200719_191905](https://user-images.githubusercontent.com/11136108/87880805-fd792680-c9f4-11ea-8e22-31ca771fa048.png)

**Comment by AFADoomer** [comment] 2020-07-19 17:54
The Astrostein shading issue is already fixed in my local repo.  Unrelated to the tracer problem.  The Earth's position was changed in a commit a while back.

**Comment by Tormentor667** [comment] 2020-07-19 18:44
> The Astrostein shading issue is already fixed in my local repo. Unrelated to the tracer problem. The Earth's position was changed in a commit a while back.

Exactly, that was intended

**Comment by AFADoomer** [comment] 2020-07-19 20:25
Tracers fixed in c629073a340495add09e699b1d834750a7dcca90.

**Closed** 2020-07-20 15:14 UTC
Labels: actor, bug, gameplay, playtesting
