### ISSUE TITLE
Missing textures for objects.

### ISSUE THREAD

**Issue by Gadgetdan** [Realm667/WolfenDoom#551] opened 2021-05-01 07:13 UTC
In HQ, you can see missing textures for the military jeep, tank, tents, Look like only the front texture is visible, not the sides or back.

**Comment by Tormentor667** [comment] 2021-05-01 07:46
Can you share screenshots?

**Comment by Ozymandias81** [comment] 2021-05-01 09:36
Yeah we need screenshots otherwise we can't understand what's going on.

**Comment by Gadgetdan** [comment] 2021-05-01 20:20
[image: image.png]

[image: image.png]
[image: image.png]

[image: image.png]


Gadget Dan .......


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Tormentor667** [comment] 2021-05-01 20:36
@Gadgetdan the message is borked

**Comment by Talon1024** [comment] 2021-05-02 14:21
Looks like it may not be possible to make images show up by replying directly to the e-mail

**Comment by Ozymandias81** [comment] 2021-05-02 14:46
Well if we won't get a reply soon, we'll consider this closed.

**Comment by Tormentor667** [comment] 2021-05-04 09:20
Got the screenshots via mail
![179591873_1010365703102012_3915375985100032398_n](https://user-images.githubusercontent.com/10298439/116983754-c5fd1180-acca-11eb-8f6c-6cc29df4e798.png)
![178648529_1956814101140811_7291063477351698447_n](https://user-images.githubusercontent.com/10298439/116983739-c39ab780-acca-11eb-80e5-50c5e86280ab.png)
![179455602_280263063758954_6989394745013023576_n](https://user-images.githubusercontent.com/10298439/116983749-c4cbe480-acca-11eb-9634-4ca2053c81a2.png)

**Comment by Talon1024** [comment] 2021-05-04 19:52
Wow, what the heck?!

It looks the vertex shaders are squishing every model into a flat plane.

**Comment by Ozymandias81** [comment] 2021-05-05 10:53
Yeah seen it somewhere too... I wonder, is it from Delta Touch?

**Comment by Tormentor667** [comment] 2021-05-15 13:19
Without knowing which engine it is and without having a second case when this happens or at least a way to reproduce it, I close this for now.

**Closed by Tormentor667** 2021-05-15 13:19 UTC
Labels: actor, mapping, playtesting
