### ISSUE TITLE
[3.1] [C2M2] Framerate starts to stutter after hitting one particular switch.

### ISSUE THREAD

**Issue by Shockwave508** [Realm667/WolfenDoom#695] opened 2021-05-26 01:05 UTC
Upon activating the switch shown in this screenshot, the framerate begins to stutter rapidly, for reasons unknown even to me. All I know is that the stuttering stops when I get knocked out and sent to the first SS Mecha fight.
![Screenshot_2021-05-25-14-40-26-410_com opentouchgaming deltatouch](https://user-images.githubusercontent.com/32436386/119587536-83dc6280-bd94-11eb-874a-e731f6d13a0c.jpg)

**Comment by AFADoomer** [comment] 2021-05-27 17:57
That line runs a script that deactivates two red lights, activates two green lights, opens a door, and sets a line special.

Can you check to see if the stutter actually starts when you leave this room and exit to the left (back to the drone area)?  A line there gets set to activate 7 drones at once after you flip this switch...  Those are a more likely culprit.

If you are getting stutter issues, useful information for us to see is the output of 'profilethinkers -t 10' in the console.  That lists the top ten worst-performing actor classes currently in the map.

**Comment by Shockwave508** [comment] 2021-05-28 05:18
I just put in "profilethinkers 1" to get the whole list, as your version of that console command didn't work.

Here are the largest numbers of actor calls that I could see...

AlertLight: 776 Calls
AlertPointLights: 359 Calls
InternalDynamicLight: 639 Calls
Overlay: 1061 Calls

**Comment by AFADoomer** [comment] 2021-05-28 05:43
Try the original command I gave again, please.  It works just fine and will sort by total think time, not just raw number of calls.

Something is obviously wrong if you have that many overlay calls showing up, though.  hmmm..

**Comment by Shockwave508** [comment] 2021-05-28 06:21
I tried your console command again, but all results have a think time of 0.000000 milliseconds.

And as for the drones...you're absolutely right; I bumrushed the entire level in Inglorious Mode just to get to that area again, and sure enough, the framerate stuttered as soon as that second set of drones woke up. Any way to fix this in the code?
[THINK2.TXT](https://github.com/Realm667/WolfenDoom/files/6558717/THINK2.TXT)

**Comment by Username-N00b-is-not-available** [comment] 2021-06-12 19:41
@Shockwave508 Does this issue still happen? Could you please try the console command again, too (with the most recent devbuild)?

**Comment by Talon1024** [comment] 2021-06-12 20:23
I personally prefer `profilethinkers t`, which shows the total time taken by each actor class.

**Comment by Username-N00b-is-not-available** [comment] 2021-06-17 20:44
This also happens for me (under OpenGL). I have a smooth picture before pressing the switch, and jittering starts after I have pressed it and **fired a shot** in the switch room (the drones have not been activated already at that time). The think time indeed jumps to around 30 or 40 ms, which is noticeable when you are playing at 35 FPS. Here is a sample of 'profilethinkers -t 10' for my machine, most of the time the results will be like the above list, but sometimes you manage to get results similar to the below one:
![image](https://user-images.githubusercontent.com/59409713/122469426-9f1e4480-cfc5-11eb-92f3-d315acde9855.png)
I suspect that lots of fodder enemies in area near (3916, 4394) and beyond hear the gunshot sound and start calling A_NaziLook or some other heavy codepointer synchronously every few tics.

**Comment by Username-N00b-is-not-available** [comment] 2021-06-21 17:18
@AFADoomer @Talon1024 What do you think about the statistics from my previous message?

**Comment by Username-N00b-is-not-available** [comment] 2021-06-22 14:20
It was because of a repeated SoundAlert call during A_NaziLook: https://github.com/Realm667/WolfenDoom/blob/4ddb3b6cab13d4ee61e9e7f5700f60a5bea27cc1/scripts/actors/enemies/base.zs#L1882
SoundAlert is a function which traverses sectors recursively, and it got called from each and every Nazi in the previously mentioned area near (3916, 4394) every 10 tics, regardless of whether he had a target before or not.
I was able to reproduce the issue and it is now fixed on my machine, please reopen the issue if something similar reoccurs.

**Closed** 2021-06-22 14:20 UTC
Labels: actor, help wanted, mapping, playtesting

**Comment by Tormentor667** [comment] 2021-06-22 20:00
Well done, really!
