### ISSUE TITLE
document not removed

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#869] opened 2021-06-20 11:47 UTC
In c2m5_b, this document is 'read', but not removed from the table.

![Screenshot_Doom_20210620_131251](https://user-images.githubusercontent.com/77861029/122672886-0eff1b80-d1ce-11eb-994c-5811b474e766.png)

**Comment by MuadDib90** [comment] 2021-06-20 12:25
I encoutered the same problem when testing C3M0_A here https://github.com/Realm667/WolfenDoom/issues/863#issuecomment-864519624, but don't know the cause yet. Probably some earlier commits...
@Tormentor667

**Comment by Username-N00b-is-not-available** [comment] 2021-06-20 12:29
It might be because of yesterday's [commit](https://github.com/Realm667/WolfenDoom/commit/68256c7edcfb22c9a48476dcc80ed346b08d03eb) by @AFADoomer, as Akten inherit from CompassItem... Not sure, just guessing.

**Comment by AFADoomer** [comment] 2021-06-20 15:09
Yeah, I'm going to have to revert that change, or just make it always return false...  we'll figure out multi-player handling for these items later.

**Comment by AFADoomer** [comment] 2021-06-20 16:14
Should be fixed after 096b6a8f514a5ab728cc84232cfbe48fe13a7ade.

**Comment by Tormentor667** [comment] 2021-06-20 16:23
Just tested, works

**Closed by Tormentor667** 2021-06-20 16:23 UTC
Labels: actor, gameplay, help wanted, playtesting
