### ISSUE TITLE
Shots blocked

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#871] opened 2021-06-20 13:46 UTC
In c3m0_b, I can't shoot the dogs from this place, because the something is blocking the shots.

![Screenshot_Doom_20210620_150839](https://user-images.githubusercontent.com/77861029/122676484-9ce30280-d1de-11eb-9f52-16add8890825.png)

**Comment by Tormentor667** [comment] 2021-06-20 16:21
I guess the hitbox of the tree model in front of you is blocking the shots. On top of that, you shouldn't even see the dogs when fog is activated :) Still, I think this is very minor and we can't perfectionize hitboxes of 3d models as of how the engine works (no complex hitboxes, only cubes) so I will close this.

**Closed by Tormentor667** 2021-06-20 16:21 UTC

**Comment by Ozymandias81** [comment] 2021-06-22 12:11
I added blocking bridges after [this issue](https://github.com/Realm667/WolfenDoom/issues/847), so better play the game as intended now :)
