### ISSUE TITLE
text moved

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1175] opened 2022-02-10 13:09 UTC
When starting a new game, c1m1, you'll get a few skip text. These are still not correctly lined up.

![Screenshot_Doom_20220210_104656](https://user-images.githubusercontent.com/77861029/153414335-fe295965-db2e-4f69-9136-58e5e29fb9e8.png)

![Screenshot_Doom_20220210_104722](https://user-images.githubusercontent.com/77861029/153414346-436fb5eb-e59c-4239-b90d-03b5339272f7.png)

**Comment by AFADoomer** [comment] 2022-02-10 23:50
I can't reproduce this...  The prompt is always displayed at the same height.  Was this before c6c99bc06df3f0ba6441b60bfa617e3c698d255a?

**Comment by x3003** [comment] 2022-02-11 09:50
Yep. You have to press space fast the 1st time and you'll get the 2nd text a little lower.

**Comment by AFADoomer** [comment] 2022-02-12 04:25
This should be fixed after 2984a38791093e19e7cdcd93da08544c14ccd4bd.  I never redid the cutscene code for this map after I reworked all of the others.

**Comment by x3003** [comment] 2022-02-12 13:51
That works fine.

**Closed** 2022-02-12 17:43 UTC
