### ISSUE TITLE
Translations of introduction letter | length discussion

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#366] opened 2021-02-07 08:32 UTC
- [ ] **INTROMAP** 
scrolling text (letter) is now longer than the page in English translation, and signature is in the middle of a paragraph. _[assigned to @AFADoomer]_ @MuadDib90 we need to make sure anway that the translations are not longer than the original english text as the paper has a fixed size --T667

> (1 Jan 21) I checked all (currently translated) languages and it looks like this: Only Czech is OK, all others need tweaks. Some of them also at the top, but definitelly all at the bottom. (I am afraid I can't do anything about other languages...) Pictures enclosed:
<details>
      <summary>Czech</summary>

![CZE (ok)](https://user-images.githubusercontent.com/73436978/103445476-c3cf6b80-4c74-11eb-8f38-c1379f9c3b6b.PNG)

</details>
<details>
      <summary>English</summary>

![ENG](https://user-images.githubusercontent.com/73436978/103445484-dd70b300-4c74-11eb-89d6-57a2c9bdde15.PNG)

</details>
<details>
      <summary>French</summary>

![FRENCH (top)](https://user-images.githubusercontent.com/73436978/103445486-e5c8ee00-4c74-11eb-8673-3fc61cc0acfe.PNG)
![FRENCH (bottom)](https://user-images.githubusercontent.com/73436978/103445492-ee212900-4c74-11eb-8bf6-cd7e262476ce.PNG)

</details>
<details>
      <summary>Italian</summary>

![ITALIAN (bottom)](https://user-images.githubusercontent.com/73436978/103445498-03965300-4c75-11eb-9f7f-b75bee287647.PNG)

</details>
<details>
      <summary>Polish</summary>

![POLISH (top)](https://user-images.githubusercontent.com/73436978/103445504-0db85180-4c75-11eb-8eb8-acc59bff8c85.PNG)
![POLISH (bottom)](https://user-images.githubusercontent.com/73436978/103445505-1741b980-4c75-11eb-8152-a7ae1f655d94.PNG)

</details>
<details>
      <summary>Russian</summary>

![RUSSIAN (bottom)](https://user-images.githubusercontent.com/73436978/103445508-245ea880-4c75-11eb-8e39-ca023b436165.PNG)

</details>
<details>
      <summary>Spanish</summary>

![SPANISH (top)](https://user-images.githubusercontent.com/73436978/103445509-2d4f7a00-4c75-11eb-9a20-c6a6dbcae5ed.PNG)
![SPANISH (bottom)](https://user-images.githubusercontent.com/73436978/103445512-35a7b500-4c75-11eb-8ecc-ee0acffaac8e.PNG)

</details>

> I adjusted the line height for the scroller text so that most languages fit better. Character spacing was changed in one of the font revamps, I think, so there's not much more I can do.  Someone will need to update some of the translations. - AFA (1 Jan 21)
>> I agree. --Muad'Dib

> @AFADoomer @MuadDib90 What about some special handling for this paper, so the raster signature graphic gets drawn after the proper line, the position of which would be indicated in the text?  --N00b, 18 Jan 2021
>> If I understood you correctly, you mean that the paper will "stretch" itself according to the length of the text, which will be defined by some mark in the text? That could be a fine solution. --Muad (29 Jan 2021)

> No, not exactly; I meant to have Blake's signature as a transparent picture in a separate file and display it in a place which will be defined by the text. But given that some texts make it outside the paper, your suggestion would also be nice to have implemented. --N00b, 06 Feb 2021
>> Glad you like my idea, but it is possible to code in some "reasonable time"? Is there anything I can help with? --Muad (6 Feb 2021)

**Comment by AFADoomer** [comment] 2021-02-07 16:38
By far the easiest way to fix this is to modify the translations.  The images here are all outdated anyway so the problem isn't as bad now.

That said:
@Tormentor667 - If we split the final text ('"Dirty" Douglas Blake') into a different LANGUAGE entry and you can provide separate images for the background paper and a transparent version of the signature, I can probably code the signature to draw in dynamically in the right spot for every language (assuming the signature is supposed to be after the closing 'Your frend and comrade' and above the printed name - which is standard style in English, at least).

**Comment by Username-N00b-is-not-available** [comment] 2021-02-07 16:45
Seconding @AFADoomer very much, this was essentially what I proposed beforehand. I'll split the texts in the CSV and try making the signature transparent now.

**Comment by AFADoomer** [comment] 2021-02-07 16:53
Actually, I was able to extract the signature already; just need the clean background paper image.

**Comment by Username-N00b-is-not-available** [comment] 2021-02-07 16:56
@AFADoomer Could you please post it? If I have the signature, I'll be able to delete its pixels from the paper and approximate the missing ones using the clean part of the paper.

**Comment by AFADoomer** [comment] 2021-02-07 17:02
Just committed it

**Comment by AFADoomer** [comment] 2021-02-07 17:07
@Username-N00b-is-not-available - Just FYI - @Tormentor667 created that original graphic, so I think may have the clean image already available.

**Comment by Tormentor667** [comment] 2021-02-07 17:26
Yeah I could have done that but you already made a good job here so there is no need to me to improve it.

**Comment by AFADoomer** [comment] 2021-02-07 17:45
OK, this should be good to go in d146cc12d8b62a24890b2e2a1fac4447d5b88ab0.

Some translations may still need tweaking if they overflow the page, but the ones I checked were good.

**Closed** 2021-02-07 18:18 UTC

**Comment by Tormentor667** [comment] 2021-02-07 19:36
Well done guys!
