### ISSUE TITLE
Can't disguise in C2M6_B

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#395] opened 2021-02-26 15:25 UTC
When on C2M6_B, when you're wearing the scientists uniform, you're actually not cloaked, so you can't continue the level and get past the guards.
The bar underneath doesn't show it and even the image in the mirror shows you're not wearing the uniform (or maybe that's how it should look like).

![Screenshot_Doom_20210226_154344](https://user-images.githubusercontent.com/77861029/109318646-509a3e00-784e-11eb-9e3a-c774afa9bde3.png)

![Screenshot_Doom_20210226_162134](https://user-images.githubusercontent.com/77861029/109319355-10878b00-784f-11eb-899b-6b7ef7255815.png)

**Comment by Tormentor667** [comment] 2021-02-26 17:52
This is strange, you should wear the scientist uniform actually and not the prisoner uniform. I just tried it with the latest version and it works fine.

![2021-02-26_185136](https://user-images.githubusercontent.com/10298439/109336470-b6dd8b80-7863-11eb-9294-79bd6be38937.jpg)

**Comment by x3003** [comment] 2021-02-26 19:30
Ofcourse i'm not playing from C2M1 on, if I just wanna try out C2M6 to see what's changed since the last time i've played it, using the changemap command. But that's no reason not changing to the scientist uniform.

**Comment by Tormentor667** [comment] 2021-02-26 20:50
I played C2 a few days ago and it worked - today I warped to C2M6_B and it worked as well. I can’t reproduce this right now but this issue is game breaking. Can you recreate it?

**Comment by x3003** [comment] 2021-02-27 01:23
I took the savegame from C3M1 I think (that's why the jail suit), can't load many others, due to loading probs when updating git versions. Then used changemap to C2M6_A and played that, reached C2M6_B and have probs disguising.
I have the latest version, so.
 When I use changemap going from C1M1 to C2M6_A, I have no prob.

**Comment by AFADoomer** [comment] 2021-02-27 01:36
You have the prisoner uniform on in C3M1_A.  When you use changemap to go to C2M6_A (and when you go to C2M6_B), you retain your inventory, so you keep the uniform on.  

The first disguise token in the player's inventory is the one that usually takes precedence, so you are seeing the camp sprites still - though this behavior is undefined, since you're not supposed to be able to have more than one disguise active at once.

If you enter 'take ccbjuniformtoken' in the console, you should see the scientist uniform.

**Comment by Username-N00b-is-not-available** [comment] 2021-02-27 07:57
@x3003 It is much easier is to use ```map CxMx_x``` instead of ```changemap CxMx_x```, this way you will just play from pistol start and not have any problems with redundant inventory items ;-)
***
By the way, we should probably ensure that every map is completable from 'pistol start' (just a console warp into this exact map). It's already possible for most maps, but there are ones like C2M5_B where you e. g. have to plant 10 C4's which are given only on the previous map.

**Comment by x3003** [comment] 2021-02-27 18:10
>When you use 'changemap' to go to C2M6_A (and when you go to C2M6_B), you retain your inventory, so you keep the uniform on.

Yes, that's right. But the game should still switch to the scientists uniform nomatter what you're wearing previously ?!

**Comment by Username-N00b-is-not-available** [comment] 2021-02-27 18:22
The code that handles the disguises just checks the player's inventory for any type of disguise items. It means that if there are two of them, the game will use the first it stumbles upon, and completely forget about the other one.
There is no map in BoA which has multiple disguises at once, two different disguises could never have ended up in your inventory without using cheats. If we are to rewrite this system, we should also somehow allow the player to manually change their disguise from inventory, but I don't see how... Maybe we can just leave the old disguise (the SS uniform in this case) on the coat hanger when you pick up the new one :-) I don't think this would be too hard to implement :-)

**Comment by AFADoomer** [comment] 2021-02-27 18:47
> 
> 
> > When you use 'changemap' to go to C2M6_A (and when you go to C2M6_B), you retain your inventory, so you keep the uniform on.
> 
> Yes, that's right. But the game should still switch to the scientists uniform nomatter what you're wearing previously ?!

No.

**Comment by Username-N00b-is-not-available** [comment] 2021-02-27 18:48
No as in [No]?

**Comment by AFADoomer** [comment] 2021-02-27 18:51
Correct.  I'm not going to fix 'bugs' that are caused by people using console commands and putting the game in a state that cannot be entered during normal gameplay.

**Comment by Username-N00b-is-not-available** [comment] 2021-02-27 18:53
Time to close the issue then. I'll put it on my list though, I'll probably play with the coat hanger idea later.

**Closed by Username-N00b-is-not-available** 2021-02-27 18:53 UTC
Labels: playtesting

**Comment by Tormentor667** [comment] 2021-02-27 18:59
> Correct. I'm not going to fix 'bugs' that are caused by people using console commands and putting the game in a state that cannot be entered during normal gameplay.

I completely agree with that. Cheating and console commands are everyone’s own risk
