### ISSUE TITLE
some items are in the wrong position

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#1407] opened 2024-04-28 20:20 UTC
These towerguards are in the wrong position. The others seem ok, but I could be wrong.

![Screenshot_Doom_20240428_220541](https://github.com/Realm667/WolfenDoom/assets/77861029/e9cbb027-0763-40a8-864a-2214184e691f)
![Screenshot_Doom_20240428_220531](https://github.com/Realm667/WolfenDoom/assets/77861029/3504f4a0-f220-429e-a2fc-9162df27fa1c)

These pieces of floor moved up:

![Screenshot_Doom_20240428_225741](https://github.com/Realm667/WolfenDoom/assets/77861029/754c522e-3166-4dfd-afdc-a4bb25ae493d)

![Screenshot_Doom_20240428_230212](https://github.com/Realm667/WolfenDoom/assets/77861029/6ce0a772-ee5b-4b4e-a1a2-ada7eebec624)

![Screenshot_Doom_20240428_230231](https://github.com/Realm667/WolfenDoom/assets/77861029/cb68bc5b-a831-4c31-a811-f36a9b866630)

These fire extinguishers are not in the right place either:

![Screenshot_Doom_20240428_225916](https://github.com/Realm667/WolfenDoom/assets/77861029/8279e2b2-794a-44f8-a78f-7649cb728717)

[the one below is actually floating]

![Screenshot_Doom_20240428_225926](https://github.com/Realm667/WolfenDoom/assets/77861029/cfc9e3ac-f4fe-4fc3-bb9a-e718647ca212)

**Comment by hawkwind3** [comment] 2024-04-28 21:40
Yep. As I suspected earlier. 3D control sectors have changed height. Remember that earlier issue with a c1 map .... Will get fixed.

**Comment by hawkwind3** [comment] 2024-04-29 01:27
Hopefully fixed now.

**Comment by x3003** [comment] 2024-04-30 21:10
Some more:

![Screenshot_Doom_20240430_224135](https://github.com/Realm667/WolfenDoom/assets/77861029/c1804e11-9214-4bb0-81d4-c1266f9927de)

![Screenshot_Doom_20240430_224143](https://github.com/Realm667/WolfenDoom/assets/77861029/aa6b02de-98ed-452b-86ea-7177032bedcd)

**Comment by hawkwind3** [comment] 2024-05-01 01:21
Exactly the same as in Boa3.1. Not a bug.
________________________________

**Comment by x3003** [comment] 2024-05-01 16:07
Maybe it was already broken in 3.1 and no one noticed ???

**Closed** 2024-06-30 06:17 UTC
