### ISSUE TITLE
Crashing after defeating the boss of the Eisenman mission

### ISSUE THREAD

**Issue by Tormentor667** [Realm667/WolfenDoom#587] opened 2021-05-07 16:28 UTC
From FreddyTheMonkey (Realm667 forums):

> Hi everyone, I downloaded the latest version of Blade of Agony with chapter 3, and I'm replaying the whole thing.
> 
> When I defeat the boss of Operation Eisenman and blow up the three crates, the game crashes. It occurs just as the "Objective Completed" popup appears.
> 
> I get the message "VM execution aborted. Tried to read from address zero" followed by some other lines (I'll write them too if it can be helpful). 

`VM execution aborted: tried to read from address zero. In function parameter "type"
Called from FireSpawner. SpawnEffect at boa.ipk3: scripts/actors/effects/fire.zs, line 84
Called from FireSpawner. StateFunction.3 at boa.ipk3: scripts/actors/effects/fire.zs, line 43
Called from EffectGiver. Tick at boa.ipk3: scripts/actors/effects/miscellaneous.zs, line 97
Called from Actor. Spawn [Native]
Called from state FireSpawner.3 in FireSpawner
Called from Thinker.Tick [Native]`

https://www.realm667.com/index.php/en/forum-board/wolfendoom-blade-of-agony/1595-crashing-after-defeating-the-boss-of-the-eisenman-mission

**Comment by x3003** [comment] 2021-05-07 19:34
There's no info what system he's running.

**Comment by FreddyTheMonkey** [comment] 2021-05-07 22:38
Sorry, I didn't think about it.

My sistem is as follows:
GPU: MSI nVidia GeForce GTX 970
CPU: Intel Core i7-4790 3,6GHz
RAM: 16 GB DDR3

**Comment by AFADoomer** [comment] 2021-05-08 01:05
This error makes no sense unless the parent fire spawner actor was removed while the function was running.  And I don't know how that could  happen.

**Comment by AFADoomer** [comment] 2021-05-08 19:18
This *should* be fixed after 09a01cec944348470b9290d4e2e18f57a0321f91.  I can't reproduce it easily, though.

**Comment by FreddyTheMonkey** [comment] 2021-05-08 19:22
> This _should_ be fixed after [09a01ce](https://github.com/Realm667/WolfenDoom/commit/09a01cec944348470b9290d4e2e18f57a0321f91). I can't reproduce it easily, though.

Thanks a lot! Should I do something on my part for resolving the issue? Download a different build or edit some files?

**Comment by AFADoomer** [comment] 2021-05-08 19:28
If you'd like to, you can replace fire.zs in the boa.ipk3 file (it's just a .7z archive) with the version in the commit full file is [here](https://raw.githubusercontent.com/Realm667/WolfenDoom/09a01cec944348470b9290d4e2e18f57a0321f91/scripts/actors/effects/fire.zs), or just move/update the two lines as detailed in the commit.

Honestly, this shouldn't interfere with continued play either way; I haven't been able to reproduce this even once - I'm just trying to cover any possible case where the command in your report could possibly be passed an invalid value.

**Comment by FreddyTheMonkey** [comment] 2021-05-09 08:19
Thanks a lot, the problem is fixed for me!

**Comment by Tormentor667** [comment] 2021-05-09 10:58
> Thank you very much, the problem is fixed for me! Can't wait to continue onwards!

Thanks for reporting back :)

**Closed** 2021-05-09 10:58 UTC
Labels: actor, bug, playtesting
