### ISSUE TITLE
Remaining definite bugs (split from old thread)

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#384] opened 2021-02-18 19:01 UTC
- [x] Need to justify offsets for machine gun effect spawners on various tank models.

> There seems to be a problem with WeaponSpot/ActorPositionable, on the Pz. IV in TEST_LDR the flare moves down when you move the main cannon up. It also does not copy the turret horizontal movement properly for some reason. Maybe some minus sign in coordinate calculations got left out?

> I'm not seeing this...  The flare rotates as expected with the view pitch. - AFA (25 Apr 2021)

> Not always... There is a problem when there is a significant difference between the player view angle and the tank gun angle: --N00b, 26 Apr 2021

https://user-images.githubusercontent.com/59409713/116105021-98580d00-a6b9-11eb-8e0f-43da3ada1963.mp4

> Ah, ok.  I think I can fix that...  the flare is moving in concert with the player view pitch, not with the pitch of the gun. - AFA (26 Apr 2021)

- [ ] C3M5_C: there is apparently a way I can make soldiers not react to gunshots and seeing the player with a weapon in the luxury interior area. After that I can just go around and kill everyone with the Blade.
> Confirmed again. --N00b, 04 Mar 2021

> How can I reproduce this?  - AFA (20 Apr 2021)

> Also a random issue, honestly I do not know how to reproduce it consistently. Could have something to do with Seeteufel's room, since there you have to open fire. --N00b, 20 Apr 2021

- [x] Missed kill on C1M3, ```netevent showliveenemies``` shows none. This happened before the paratroopers' landing, I do not know which actor could it be.

![Screenshot_BoA_20210425_165219](https://user-images.githubusercontent.com/59409713/116001373-d6dbc200-a5fc-11eb-8669-64a7c13f705f.png)

- [x] Additional kill on C1M6, it occured before the boss battle, but sadly can't provide details. This is why I have 100% on the ending screen ;-)

![Screenshot_BoA_20210425_192301](https://user-images.githubusercontent.com/59409713/116001386-e1965700-a5fc-11eb-9c28-927b678b172d.png)

**Comment by Username-N00b-is-not-available** [comment] 2021-02-20 14:37
<details><summary>Resolved issues</summary>

- [x] C3M0_A: monk near (12154, 3850, -224) does not see the player. Same with Gen. Totengraeber.
- [x] C3M0_A: can't reach loot from barrel near (5442, 20064, 768).
- [x] C3M0_A: got 4 of 5 treasure items (all of them in the cinema), can't find the last one.
- [x] C3M3_B: 80/81 items, can not find the missing one. I searched literally every corner with double iddt + editor, no idea where (and what) it could be.
- [x] C3M4: 145/146 items, can't find the last one (I've successfully taken the coin from the previous checkbox).
- [x] C3M5_B: 164/168 kills, I don't get at all where the remaining enemies could be. Triple-checked the automap and the editor, no clue. No moving enemies on map, no standing ones. If it helps, if I do 'kill Nazi' in the console after that I can hear Hans Grosse's death sound.

> And now the death sound is 'Scheisskopf!' --N00b, 07 Feb 2021
- [x] C3M5_C: Ascher's 'talking head' in SS uniform in the radio messages does not play its animation.
- [x] C3M5_C: 54/55 items.
</details>

**Comment by Ozymandias81** [comment] 2021-02-25 09:24
Sorry for my absence in these times, but something terrible happened in my family... My mother died some days ago and I have to reinvent the wheel of my life, this is also why my work has been very vague and discontinue for some months, had to take care her 24h. I do hope things will get better after middle of March and go through all issues and see what I can fix or not. Thank you kindly for the effort on fixing stuff, just remember to keep intact our ideas without alter them too much, unless this is strictly required for the fix.

**Comment by Username-N00b-is-not-available** [comment] 2021-02-25 11:16
My sincere condolences on your loss. Please do properly everything you should do in these circumstances, everything else is nil in comparison to that and can wait.

***

As for the fixes and ideas, I understand that and try to remind myself frequently about what you said. I would change the team's ideas only after a thorough discussion (and e. g. this is what #383 is for).
We are looking forward to your getting back, but once again, please take your time!

**Comment by Tormentor667** [comment] 2021-03-13 17:47
Fixed everything I could so far.

**Comment by Tormentor667** [comment] 2021-03-31 18:35
Summoning @Talon1024 @AFADoomer @Ozymandias81  for the last remaining issues here - I guess most of it is code-specific and I unfortunately can't help here except testing.

**Comment by Username-N00b-is-not-available** [comment] 2021-04-01 17:03
Recently, there was a player report that, for most enemies, the player's bullets freely pass through their heads (=their hitboxes are too short). More than a year ago @AFADoomer fixed this in https://github.com/Realm667/WolfenDoom/commit/6b6ab64adcfef2dd155dd9cdbf5ba59a10f2bc4f to some extent, adding 8 units to the base height, but the effect is still noticeable. What is the team's opinion, should we change it now (by adding another 4 or 8 to the actors' height)?

**Comment by Tormentor667** [comment] 2021-04-01 17:22
I never noticed this on my own actually. What's the difference between the visual height and the actual hitbox height?

**Comment by AFADoomer** [comment] 2021-04-01 17:26
Most if the head on a standard guard.  

You can see this with the crosshair overlays, too.  The knife/target/don't shoot image disappears as you move your aim above the shoulders of most guards.

**Comment by Tormentor667** [comment] 2021-04-01 17:28
Thanks for clarifying. Well, I am actually okay with how it is now, but if you guys want the hitbox larger with about 4-8 units, it's okay for me as well. I just hope that it doesn't interfer with level geometry somewhere. At this stage of development we need to be careful with such global changes.

**Comment by AFADoomer** [comment] 2021-04-01 17:30
That's my worry, too.

**Comment by Talon1024** [comment] 2021-04-01 18:19
I remember something being mentioned in the "Visual actor hitbox debug" thread on ZDoom forums... If I can find it, that is...

**Comment by Tormentor667** [comment] 2021-04-02 07:29
> That's my worry, too.

So would it be ok for everyone if we keep it as it is?

**Comment by Ozymandias81** [comment] 2021-04-03 19:06
I say keep it as is for now

**Comment by AFADoomer** [comment] 2021-04-03 19:07
Agreed.  Not worth the possible problems that it could cause.

**Comment by Ozymandias81** [comment] 2021-04-07 11:51
Working on C3M5_A, so please no one touch it before I commit my work

**Comment by Tormentor667** [comment] 2021-04-08 17:12
Are you done with it @Ozymandias81 ?

**Comment by Ozymandias81** [comment] 2021-04-09 13:05
Yes sorry for late reply, just gonna check the machinegun fire thing killing easily companions

**Comment by Ozymandias81** [comment] 2021-04-09 16:34
While I am done with C3M5_A, I think I might have found something related to [treasure items not being count sometimes](https://github.com/Realm667/WolfenDoom/search?q=CoinDrop)... While I don't remember exactly why CoinDrop class has been added (most probably for items which may fall somewhere and not being possible to pick up, or something else), it may be the cause of some issues related here , such as missing items or spies coins
What do you think @Talon1024 , could be that? And if yes how to fix it in a secure way?

**Comment by Talon1024** [comment] 2021-04-09 17:48
The CoinDrop class was added for the Totale Gier powerup, which makes enemies drop money when they are killed if you have the Totale Gier powerup active.

**Comment by Talon1024** [comment] 2021-04-09 22:09
> C2M5_B: the zaps do not work properly, the player can pass through most of them without receiving any damage.

Which ones? The ones at the end, or the ones blocking the V2 and hangar?

**Comment by Username-N00b-is-not-available** [comment] 2021-04-10 06:29
@Talon1024 The ones at the end, their 'hitbox' seems to be much smaller than the scaled models themselves.

**Comment by Tormentor667** [comment] 2021-04-13 19:26
Rechecked the list. Unfortunately I can't help with any of the remaining bugs.

**Comment by AFADoomer** [comment] 2021-04-14 03:54
Most of the item and kill count issues should be resolved now, I think.

I added handling so that inactive sneakable actors that are removed via script now get properly removed from the kill count, and added a bunch of ClearCounters() calls to places where items that we don't want to count to the totals are spawned (like with SpyGive, which is what is also used by the reward script in C3M6_A).

**Comment by Username-N00b-is-not-available** [comment] 2021-04-18 10:02
Does anybody have ideas on how to fix the remaining issues here?

- C2M3 and C3M6_A portals: I tried changing geometry near the portal planes, but to no effect. I am not sure what could cause this, maybe it is related to some obscure check in our player movement code.
- Zapping lightnings on the ending lift in C2M5_B: @Talon1024, you showed some interest in this a few days ago, do you have any guesses on why this could happen? I think it is probably because of some miscalculation in the collision code for lightnings.
- C3M0_A treasure item count: the gold does not spawn in world. This can also be seen with all other scripted gold gifts, e.g. load up @AFADoomer's score.pk3 ([this one](https://github.com/Realm667/WolfenDoom/issues/459#issuecomment-821892570), as the old version will now induce a crash), go to TEST_LDR, then spawn and kill 16 `PlagueDoc`s. The total treasure amount will raise, but not the picked up item amount.
Maybe we should just add -COUNTITEM gold item variants for cases when we need to add some gold via scripts?
- C3M0_A Nemesis table problem: it is inevitable that with such large changes in actor movement logic we have some subtle errors. This could be disregarded to be fixed after the release.
- C3M0_B problems: likely irreproducible consistently, but can show up any time. Could be also left for fixing later.
- Machinegun offsets on tank models: quite minor, definitely not the top priority.
- C3M5_C stealth problems: these have also a long history, and I doubt we can do much about it anymore. It could be anything that interferes with the proper behaviour: specific actors, ACS oddities, non-obvious problems in the stealth code. I think it is better to wait for several bug reports which show how to reproduce such bugs. As for myself, when I discovered them, I was not able to isolate the possible source.
- Friendly Nazis/PlayerFollower problems: might be as easy to fix as adding one condition to the PlayerFollower code, or might be a fundamental engine restriction. Honestly, I do not know.
- Zombie blood issue: minor, dated, and occured only one time for me.
- SM03 screen flash: has this been fixed? It seems the same happened for at least three testers (including myself): #465, #482.
- Totale Gier gold drop: might not be a very important issue, but this behaviour could also result in item count problems.

**Comment by Tormentor667** [comment] 2021-04-18 14:17
I unfortunately can't help here.

**Comment by Ozymandias81** [comment] 2021-04-18 18:50
The thing about c2m3/c3m6_A is related mainly to how ladders behave and probably the wallrunning feature in idtech1 engine, but it is just [an assumption](https://github.com/Realm667/WolfenDoom/commit/459c7e827bb777584844f026d7367e9c431a22f2#diff-59515cdb239e540f0aebab2e9ebe9902bc0acca113b450fd590661bc79416ba6).

**Comment by AFADoomer** [comment] 2021-04-19 03:27
What do I need to do to reliably recreate the problem with the ladder?

**Comment by Username-N00b-is-not-available** [comment] 2021-04-19 21:00
For the ladders and portals, maybe we can load the map geometry with plain Doom II (+ loading all classes needed for ladders to work, but only them) and test the behaviour? This could help isolate the problem: if it still occurs, the problem is likely either in ladders code or in the engine; if it doesn't, the problem is likely in BoA player movement code.

**Comment by Username-N00b-is-not-available** [comment] 2021-04-20 16:00
@AFADoomer Yes, it really does happen consistently! [fly_portal.zip](https://github.com/Realm667/WolfenDoom/files/6344899/fly_portal.zip) (for Doom II) Collisions with the lower part of the portal seem to work fine, but not with the upper part... I think we should report this to GZDoom developers.

**Comment by AFADoomer** [comment] 2021-04-20 22:37
PlayerFollower and Medic issue fixed in a82b7d0791467291c8c49b3c4d767f84f588235b.

**Comment by nashmuhandes** [comment] 2021-04-21 14:44
Sorry if this is reply is in the wrong format but I noticed I was pinged for the lens flare shader - just a correction from me, that I did not write that shader.

**Comment by Username-N00b-is-not-available** [comment] 2021-04-21 16:16
It seems that the shader is from Total Chaos (after searching this string ```fc += vec4(fsrc.rgb, 1.0);``` in Google this result popped up: https://forums.thedarkmod.com/index.php?/topic/20175-view-shrinks-while-underwater/&do=findComment&comment=441625)

**Comment by Tormentor667** [comment] 2021-04-21 16:51
Yes that’s right!

**Comment by AFADoomer** [comment] 2021-04-21 17:03
> Sorry if this is reply is in the wrong format but I noticed I was pinged for the lens flare shader - just a correction from me, that I did not write that shader.

Ah, sorry.  The original commit referenced you.  My bad!

**Comment by Username-N00b-is-not-available** [comment] 2021-04-22 07:37
A new problem with text colouring in radio messages:
![Screenshot_BoA_20210422_103207](https://user-images.githubusercontent.com/59409713/115674526-690e6c80-a356-11eb-8f22-6542cced3e00.png)
Some text lines start with wrong text colours. This happens inconsistently, but not only in English. I checked the CSV, everything there seems to be written properly.

**Comment by Username-N00b-is-not-available** [comment] 2021-04-22 13:32
This issue is also mostly dealt with, only a few slight problems remain (I just wonder if the bug report on portals and flying would be noticed by GZDoom developers before 30 April...) Excellent work!
Thank you very much, team, for noticing my feedback and working to fix the problems over time. (Open the spoiler in the second post https://github.com/Realm667/WolfenDoom/issues/384#issuecomment-782691313 to see how much we managed to do in collaboration within just a few months! Not to mention there were lots of issues with lots of bugs and suggestions, including ones opened by myself, and many more other ones.)

**Comment by AFADoomer** [comment] 2021-04-22 14:59
I just bumped the ZDF bug post with some additional clarifying explanation.  Hopefully that will generate some discussion.

**Comment by Username-N00b-is-not-available** [comment] 2021-04-23 15:28
@AFADoomer Regarding the machinegun flare offsets on tanks: there seems to be a problem with WeaponSpot/ActorPositionable, on the Pz. IV in TEST_LDR the flare moves down when you move the main cannon up. It also does not copy the turret horizontal movement properly for some reason. Could you please investigate what's going on with this, maybe some minus sign in coordinate calculations got left out?

**Comment by Username-N00b-is-not-available** [comment] 2021-04-23 15:34
Another problem, also noticed a long time ago: if you load a savegame (or just warp to another map, but that's a cheat) while being in a tank, the chasecam cheat stays enabled. This is IIRC default GZDoom behaviour, but I wonder if there is a way for it to be disabled.

**Comment by Tormentor667** [comment] 2021-04-23 19:28
> Some text lines start with wrong text colours. This happens inconsistently, but not only in English. I checked the CSV, everything there seems to be written properly.

I've noticed this as well, it falls back to a different color when a new line begins but I have no idea if this is caused by GZDoom or our mod. This is a critical bug, we definitely need a solution here.

**Comment by Talon1024** [comment] 2021-04-23 19:31
> I've noticed this as well, it falls back to a different color when a new line begins but I have no idea if this is caused by GZDoom or our mod. This is a critical bug, we definitely need a solution here.

[I think I've already reported that](https://forum.zdoom.org/viewtopic.php?f=2&t=71744), and Graf seems to have said that certain old mods rely on this broken behaviour. I guess the best we can do is look for where the text colour is incorrect, and fix the text colouring manually. I already did that for the URLs in the developer comments, BTW.

**Comment by Username-N00b-is-not-available** [comment] 2021-04-23 19:59
We can do it for one, two, ten occasions, as you did with the URLs, but there are hundreds of radio messages in BoA which could need the treatment — and for each message in each language you cannot know without testing if it will happen or not, and if it will, which ones of the words will need a crutch!
This is honestly sad. Maybe we can persuade Graf to add a new ACS function instead of HudMessage/HudMessageBold, which would use a corrected version of V_BreakLines, and deprecate HudMessage for good..? The source of the problem is already almost localized (there is even a comment at line 136).

**Comment by AFADoomer** [comment] 2021-04-24 02:41
This happens because the code does not account for colors that are defined after the space that ends up being use to split the string into lines...  

In the example above, when the code parses through "rescue us...\U*krzz", it remembers the space between 'rescue' and 'us' as the last possible line break that it has encountered, then continues parsing and saves 'U' as the last encountered color.  At some point after that, the code sees that max width has been hit, so it chops the line off at the last remembered space (so, before "us"), and starts the next line off with the last encountered color (which is still 'U', despite that portion of the string no longer being part of the line).

acc8c0ce459216b41ddad9062804f0856cfdeddd adds some functionality to fix this logic.

**Comment by Tormentor667** [comment] 2021-04-24 06:49
Thanks a lot @AFADoomer , this fix was very important!

**Comment by Username-N00b-is-not-available** [comment] 2021-04-24 16:25
@AFADoomer, ActorSpawner placed into a sector with lightlevel 64 gives a division by zero VM abort:
![image](https://user-images.githubusercontent.com/59409713/115965568-90ba2c00-a532-11eb-8782-260750cbd9f3.png)

**Comment by Username-N00b-is-not-available** [comment] 2021-04-25 08:16
@AFADoomer This problem with HudMessage colours sadly still happens for me after the recent commits (https://github.com/Realm667/WolfenDoom/commit/e805848d6a49e076df29a4f0e2823f702ac213f2):

![Screenshot_BoA_20210425_110815](https://user-images.githubusercontent.com/59409713/115985960-d7ea0080-a5b6-11eb-99fc-b02791bccf6c.png)

There's also this (WaveSpawner referenced for some reason instead of the use key, same happens in English):

![Screenshot_BoA_20210425_110426](https://user-images.githubusercontent.com/59409713/115985955-d4567980-a5b6-11eb-88b2-7b6501822826.png)

Both screenshots are from the SS HQ in C3M0_A.

***
By the way, on the currently-last issue, what do you think about lowering MaxStepHeight for tank players to 32? https://github.com/Realm667/WolfenDoom/blob/f43e95c44bdcca0c38bf153eff7fc2a0f7458c90/scripts/actors/tank.zs#L62

**Comment by Username-N00b-is-not-available** [comment] 2021-04-25 14:19
@AFADoomer Safe text hints can not be scrolled properly to next page (it reverts to first page). Same happens with the safe menu (tested on C1M3). Could be related to recent menu rework.

**Comment by AFADoomer** [comment] 2021-04-25 14:31
The code for those doesn't intersect with the menu changes in the slightest...

Did you mean C1M4?  I can't recreate what you are describing...  The pages scroll as expected, and the safe works as expected.

**Comment by Username-N00b-is-not-available** [comment] 2021-04-25 14:52
@AFADoomer Yes, C1M4, sorry. I am trying to playtest C1 now with https://github.com/Realm667/WolfenDoom/commit/f48721a3c3f48defae9c9c0fec02e5c71159d14a, and bumped into this. Cannot reproduce it even now, it was likely a machine-specific problem.
Got it for the tanks, and Talon's commit probably fixed the <use> messages, I'll test it once I finish C1. I would like to ask you again about the HudMessage problem and this https://github.com/Realm667/WolfenDoom/commit/acc8c0ce459216b41ddad9062804f0856cfdeddd#comments commit, was your intention to fix the text colouring with it?
Also, on problems related to HUDs, the following entry (PRISONERMESSAGE01) does not show a full stop/period after the last word in Russian (it is present in the CSV and was on the commit I am playing). In English everything with it works well.
![Screenshot_BoA_20210425_162721](https://user-images.githubusercontent.com/59409713/115998073-3c748200-a5ee-11eb-810a-c92d9a50f495.png)

**Comment by AFADoomer** [comment] 2021-04-25 15:42
Yeah, I'm trying to fix some of those issues now.  The unicode character parsing is giving me headaches...  I had it displaying perfectly in Russian, and then it was mangling line endings/colors for everything in Latin alphabets...

It was @Talon1024 that added the line breaks to conversation text cells (I actually removed one so that I could test more easily).  They should be unnecessary now, but the colors are sometimes still broken for non-ASCII-range alphabets.

**Comment by AFADoomer** [comment] 2021-04-25 16:29
OK, the line breaks and string colors should be fixed in 9da29eea54667033baf54f657a361e35579cabcd.

**Comment by Username-N00b-is-not-available** [comment] 2021-04-25 16:45
Have done a full C1 playthrough on skill 0 in Russian just now:
![c1full](https://user-images.githubusercontent.com/59409713/116001292-6d5bb380-a5fc-11eb-97c5-df226d58da81.png)
Though this could only be considered as a sanity check compared to a full-game playthrough (2 hours vs. 13 hours), nevertheless I managed to find some nitpicks:

![Screenshot_BoA_20210425_192557](https://user-images.githubusercontent.com/59409713/116001403-efe47300-a5fc-11eb-905f-af7079e9239a.png)

<details><summary>List</summary>

- [ ] (very old bug) This mechanic on C1M2 does not react to any gunshots, if they do not hit him.

![Screenshot_BoA_20210425_161704](https://user-images.githubusercontent.com/59409713/116001369-d2afa480-a5fc-11eb-875e-36d5d43204af.png)

- [ ] Missed kill on C1M3, ```netevent showliveenemies``` shows none. This happened before the paratroopers' landing, I do not know which actor could it be.

![Screenshot_BoA_20210425_165219](https://user-images.githubusercontent.com/59409713/116001373-d6dbc200-a5fc-11eb-8669-64a7c13f705f.png)

- [ ] C1M5: this 'You Failed' message after the second bridge destruction just overlays the screen, and you cannot press 'use' to restart, as you are not dead. Very nitpicky, but easy to resolve by either adding a script which listens for the use command or plain killing the player.

![Screenshot_BoA_20210425_173117](https://user-images.githubusercontent.com/59409713/116001379-dc390c80-a5fc-11eb-848e-8c968b572034.png)

- [ ] Picking the Grail up does not kill a well-stacked player on skill 0, only severely damages them.

![Screenshot_BoA_20210425_191349](https://user-images.githubusercontent.com/59409713/116001380-dcd1a300-a5fc-11eb-911b-b4823cf0d4f0.png)

- [ ] Additional kill on C1M0, it occured before the boss battle, but sadly can't provide details. This is why I have 100% on the ending screen ;-)

![Screenshot_BoA_20210425_192301](https://user-images.githubusercontent.com/59409713/116001386-e1965700-a5fc-11eb-9c28-927b678b172d.png)

- [ ] Once again, the endboss health bar is shown incorrectly _on skill 0_, you have to shoot the boss down to half its health for the health bar to start decreasing.

![Screenshot_BoA_20210425_192347](https://user-images.githubusercontent.com/59409713/116001391-e6f3a180-a5fc-11eb-9732-925627704641.png)

</details>

Overall impression: everything is done really well, this is definitely ready for the release!

**Comment by Tormentor667** [comment] 2021-04-25 16:55
Fixed two of the mentioned bugs.

**Comment by Username-N00b-is-not-available** [comment] 2021-04-25 17:52
@Tormentor667 What is the second one you have fixed? The Grail?

**Comment by Tormentor667** [comment] 2021-04-25 18:32
Yes, sorry, forgot to check it

**Comment by AFADoomer** [comment] 2021-04-25 21:51
I figured out what the problem is with the smoke monster...  And why it was working fine in my test map.

C1M6 (script 49) was seting the monster's health to 3000, regardless of skill setting.  So the bars weren't right on any of the lower skill levels.  Fixed in 00f295f2b4068e9016363531d579f995d9427a4c.

**Comment by AFADoomer** [comment] 2021-04-26 02:36
Fixed the C1M5 respawn issue in cc17e261c36eedf9dc865df2e21dcf07c60d74dd.  All players are now killed when the mission is failed, so can restart the map by pressing use as normal instead of being forced to reload a save.

**Comment by Ozymandias81** [comment] 2021-04-26 17:00
Low health graphics aren't 4:3 friendly it seems, I said this already in [this commit](https://github.com/Realm667/WolfenDoom/commit/703f8a43bee7da01c47ee6c19e56e3ce9d65b577)... I got that issue under r196 with 1024x78 resolution

https://ibb.co/n3gsCf1

**Comment by Talon1024** [comment] 2021-04-26 17:08
> Low health graphics aren't 4:3 friendly it seems, I said this already in [this commit](https://github.com/Realm667/WolfenDoom/commit/703f8a43bee7da01c47ee6c19e56e3ce9d65b577)... I got that issue under r196 with 1024x78 resolution

I have no idea if anything can be done about that... The only thing I could think of is to scale it up to 5:4 resolution, and add offsets to it.

**Comment by Username-N00b-is-not-available** [comment] 2021-04-26 17:17
I know I'll get stoned for this, but what about exporting the low health display to ZScript? Not the full logic (it could stay in ACS), only the part which shows the red graphic. It could be shown fullscreen just like in IWADNotice.

**Comment by AFADoomer** [comment] 2021-04-26 17:28
That's probably the best way to fix it.  A simple wrapper to a Screen.DrawTexture call using DTA_FullscreenEx for now.  Probably good to update all of the overlay code to ZScript for 3.1.

**Comment by Username-N00b-is-not-available** [comment] 2021-04-26 20:24
Honestly, I'm doing this right now...

**Comment by Tormentor667** [comment] 2021-04-26 20:28
Thanks kindly, I am online with my mobile phone, I would have done it myself otherwise :)

**Comment by Talon1024** [comment] 2021-04-26 20:32
You'll need to put the code in an overridden RenderOverlay or RenderUnderlay method in an event handler.

**Comment by Username-N00b-is-not-available** [comment] 2021-04-26 20:39
Argh, there is also the ```HealthScriptDeactivate``` ACS global variable used to deactivate the snippet. The overlay is only drawn when it is false. I doubt there is a good way to access ACS global variables from ZScript... Is this ```HealthScriptDeactivate``` variable used in maps?

**Comment by AFADoomer** [comment] 2021-04-26 20:44
It is used in C3M1.

**Comment by Talon1024** [comment] 2021-04-26 20:44
Yes. Here are the maps which reference it:

    Binary file maps/SM01.wad matches
    Binary file maps/C2M1.wad matches
    Binary file maps/SM03.wad matches
    Binary file maps/C3M0_B.wad matches
    Binary file maps/CUTSCEN2.wad matches
    Binary file maps/SM02.wad matches
    Binary file maps/C3M1_A.wad matches

If the variable is defined as a "global" (as in `global int 10:something`), you can access it via ZScript by using `BaseStatusBar.GetGlobalACSValue(int index)`

**Comment by Username-N00b-is-not-available** [comment] 2021-04-26 20:54
OK, good to know. Thank you! Tomorrow I'll continue with ithis (it's nearly midnight in Moscow, and I'm really tired...)

**Comment by Username-N00b-is-not-available** [comment] 2021-04-27 10:17
@Talon1024 @AFADoomer I committed a change to a separate branch https://github.com/Realm667/WolfenDoom/tree/acsoverlays, there are some problems with ice damage and adrenaline overlay, could you please help me?

**Comment by Username-N00b-is-not-available** [comment] 2021-04-28 19:44
Tested C2M1, looks seamless, and you can also 100% it. More C2 maps maybe coming tomorrow.

**Comment by Ozymandias81** [comment] 2021-04-29 11:20
Regarding C1M3, if I remove the End Level special from Darren and kill monsters, I always get this MGTurretSoldierW alive, while in place there is already a dead soldier down its feet.
![Screenshot_Doom_20210429_131835](https://user-images.githubusercontent.com/11136108/116543052-ad1ce680-a8ed-11eb-90f2-860301a6bdd0.png)

**Comment by AFADoomer** [comment] 2021-04-29 13:22
C1M3 killcount should be fixed as of 2f4fee784c0216b707b68033e36b423dbf5f47fe.

When the turret soldier is killed, the soldier next to him takes over the turret.  Internally, this means that the soldier is removed and a new soldier-manned turret is spawned.  Previous to the commit referenced above, the original soldier was destroyed bu would never be removed from the max kill count for the level, so the max kills number was off by one for every time a new soldier took over a turret.

**Comment by Username-N00b-is-not-available** [comment] 2021-04-29 14:23
Finished C2. Important problems (there also are some misalignments and stuck enemies here and there, but let's spend time on them after the release):

- [ ] C2M5_B: @AFADoomer In Russian this Douglas message (DARRENMESSAGE80) is not displayed fully. It should end with
`Запустишь — уноси ноги!` (the variant in the CSV)
instead of 
`Запустишь — уноси`:

![Screenshot_BoA_20210429_144201](https://user-images.githubusercontent.com/59409713/116565594-ae124000-a90e-11eb-8f1c-39e1cdefc23d.png)

- [ ] C2M6_B: 191/193 enemies can be killed. `kill monsters` kills 17 enemies, but countkill stays the same, `netevent showliveenemies` shows none.

Will not do C3 (fully, at least), sorry.

**Comment by Tormentor667** [comment] 2021-04-29 17:49
Finished playing C1 and some random C2 maps without any flaws. Will continue later with the critical C3 ones. Maybe we can split that up, what do you think?

**Comment by Username-N00b-is-not-available** [comment] 2021-04-29 17:58
@Tormentor667 OK, which maps you would like to play yourself?

**Comment by Ozymandias81** [comment] 2021-04-29 20:03
I think the most important to be verified is the final battle on C3.

**Comment by Tormentor667** [comment] 2021-04-29 20:47
Playing C3M1 and C3M6 now. I think someone should at least take care of C3M0_A and C3M0_B, as these are both a bit more complicated.

**Comment by Tormentor667** [comment] 2021-04-29 21:42
C3M1_A/B are working like a charm, didn't find anything critical.

**Comment by AFADoomer** [comment] 2021-04-29 23:53
I think the C2M6_B count issue might be fixed after db7337fa03c6f0218ad9d06b98997ce426a6e9f8.  At least, killing all monsters via console at the start of the map shows 100% now.

**Comment by Username-N00b-is-not-available** [comment] 2021-04-30 07:43
Damn it! I must have accidentally deleted a screenshot yesterday and forgot to report that

- [ ] Sneakable patrolling enemies killed by player's deployable mine explosion do not increase kill count.

You can test it on C2M6_B in the submarine hangar (there are companies of Wehrmacht guards patrolling the area).

@Talon1024 @AFADoomer @Ozymandias81

**Comment by Ozymandias81** [comment] 2021-04-30 08:32
I think it was maybe related to this [fix](https://github.com/Realm667/WolfenDoom/commit/9a3b63f3db85970e237d4d14868445b273784fdb)?

**Comment by Username-N00b-is-not-available** [comment] 2021-04-30 08:51
@Ozymandias81 Unlikely, as it happened in other part of the map (to test just use `notarget`, warp to (5000, 2700), `give deployablemine` and place the mine on path of one of the enemies).

**Comment by Username-N00b-is-not-available** [comment] 2021-04-30 09:29
@Tormentor667 C3M0_A done. The only problem I noticed was that on many doors the side with the lock was mixed up with the opposite one, such as here:

![Screenshot_BoA_20210430_115610](https://user-images.githubusercontent.com/59409713/116676383-963ec880-a9af-11eb-8b3a-0d81e171da36.png)

Time for me to fix the doors now. After that going to test C3M0_B.

**Comment by Tormentor667** [comment] 2021-04-30 10:45
> C3M0_B: Mutants are unable to escape the cages after they are broken, they just run in their places:

Is the line-unblocking not working or are the steps too hight? Could be one of these...

**Comment by Username-N00b-is-not-available** [comment] 2021-04-30 10:47
@Tormentor667 Yes, it seems the lines are not unblocking.

**Comment by Tormentor667** [comment] 2021-04-30 11:44
I am currently at work (13:44, until 17:30), will you take care of it or should I do that this evening?

**Comment by Username-N00b-is-not-available** [comment] 2021-04-30 11:54
@Tormentor667 I'll try to take care of it, I'll report if it goes wrong.

**Comment by DoomJedi** [comment] 2021-04-30 12:10
"about mutant issue, I think it is related with umproper usage of line_setblocking, because if it has been used deprecate setlineblocking special that may cause issues (maybe)" (Virg)

**Comment by Username-N00b-is-not-available** [comment] 2021-04-30 12:11
@DoomJedi Yes, exactly that.

**Comment by Username-N00b-is-not-available** [comment] 2021-04-30 13:52
Commander Keen levels seem to have some problems with flat offsets... I'll fix them after playtesting SM03.

**Comment by Tormentor667** [comment] 2021-04-30 14:33
Except the teleporting, it's nothing too critical atm fortunately. But it needs to be adressed.

**Comment by Username-N00b-is-not-available** [comment] 2021-04-30 14:57
@Tormentor667, have you tested C3M6_A/B?

**Comment by AFADoomer** [comment] 2021-04-30 15:12
Smirky should already try to teleport again if stuck in a wall...  not game-breaking either way, at least.

**Comment by Tormentor667** [comment] 2021-06-05 12:59
@Username-N00b-is-not-available would you be so kind and open single issues for each remaining bug in this bug-report thread here? It's easier to track things that way.

**Closed by Tormentor667** 2021-06-05 12:59 UTC
Labels: actor, bug, help wanted, playtesting
