### ISSUE TITLE
SM02: Broken bridge

### ISSUE THREAD

**Issue by Talon1024** [Realm667/WolfenDoom#333] opened 2021-01-07 08:55 UTC
I tried to do a playthrough of SM02, and I got stuck because a certain bridge wasn't being activated.

https://user-images.githubusercontent.com/6550500/103872211-13aa9a00-509c-11eb-9612-0f6efe4ac262.mp4

**Comment by Tormentor667** [comment] 2021-01-07 16:09
This is strange, I just tried it and it works for me. Could it be that some actor is blocking the 3d floor from rising? I spawned objects on the bridge and below it, switching it on and of and repeated it but it worked for me.

**Comment by Ozymandias81** [comment] 2021-01-07 16:13
Works for me as well, it's strange indeed, everything's set... maybe there are duplicate tags? Checking
![Screenshot_Doom_20210107_171156](https://user-images.githubusercontent.com/11136108/103915516-9880cc80-510b-11eb-8be7-272cc9a5b834.png)

**Comment by Talon1024** [comment] 2021-01-07 16:22
Well, it only happened on one particular run of SM02, so the issue is sporadic, and I didn't have the issue when I went through this map a second time. I don't know what happened to cause it.

**Comment by Ozymandias81** [comment] 2021-01-07 16:24
Works as IWAD under r37 so maybe it is like Torm said
![Screenshot_BoA_20210107_172244](https://user-images.githubusercontent.com/11136108/103916793-21e4ce80-510d-11eb-81fa-b424c7e3a283.png)

**Comment by Talon1024** [comment] 2021-01-09 01:16
I just looked at my savegame where the bridges were broken, and somehow, two of the bridge 3D floor control sectors were flat. In addition, I noticed they moved up to 10000+ instead of moving down to <= 1000.

**Comment by Ozymandias81** [comment] 2021-01-09 13:17
Maybe something related to gzdoom? Was you testing from builder too?

**Comment by Tormentor667** [comment] 2021-01-10 14:33
> I just looked at my savegame where the bridges were broken, and somehow, two of the bridge 3D floor control sectors were flat. In addition, I noticed they moved up to 10000+ instead of moving down to <= 1000.

Very strange, it feels like a "one-in-a-million" engine/game bugs to me. Should we simply consider this too unreproducable to be even fixable and close it?

**Comment by AFADoomer** [comment] 2021-01-10 18:38
I just re-worked the bridge movement script to use absolute values instead of height offsets, so that even if this does continue to happen (though I can't see how it will), re-activating the switch a couple of times will fix it.

**Closed** 2021-01-10 19:21 UTC
Labels: gameplay, playtesting
