### ISSUE TITLE
Actors which need to be fixed or improved, part II

### ISSUE THREAD

**Issue by Username-N00b-is-not-available** [Realm667/WolfenDoom#294] opened 2020-09-28 19:32 UTC
Something more on tanks.

- [x] Very minor, but I think it would be nice to add initial velocity to the muzzle flash and cloud, it can now spawn in the gun if the tank is moving: <details> ![Screenshot_Doom_20200930_133906](https://user-images.githubusercontent.com/59409713/94732208-9ff74380-036e-11eb-8ae5-82bd1eb81baf.png)</details>

> In recent commits I have done this. --N00b

- :x: T-34-85 model is very large and high, it is bigger than Tiger almost by half. In reality these tanks had such dimension parameters (T-34-85 is left, Tiger is right, and vice versa on the picture):
> This nitpick will turn us to deal with offsets for all actors and models for both tanks, and also rework fake hitboxes on maps where they are placed as decorations... Again have to say, not important. --Ozy81 I agree here, why this can be ignored --Tormentor667<details> Height: 2700 vs 3000
Width: 3000 vs 3705
Length (without turret): 6100 vs 6316
![](https://i-a.d-cd.net/8811cbes-960.jpg)</details>

>Ok, I get it, but it is mostly the issue with T-34, it is too big and unproportional, and looks literally like this:

![comparison](https://user-images.githubusercontent.com/59409713/97595341-a8e24000-1a14-11eb-8e24-ef5009561d4a.png)

>I mentioned Tiger just for comparison --N00b

- [x] Spies which give you items do not control if your inventory is full, e.g. if you already have 5 bandages and the spy gives you one, it is wasted. Same goes for 9mm ammo. Please add a check so in such situation the spy would just drop the item near player, so they can return and reclaim it later, when they need it.

> This was addressed recently. --N00b

:x: For some reason 'kill monsters' does not massacre all the tanks on map, it kills them one by one. Quite strange.
> I am not sure but it may be related to the fact that Tanks are split in a couple of actors each, but anyway this is cheats related so we can live with it as well. --Ozy81

- [x] Would be nice to add some sprites for the C3M5_A surrendering soldier key and also C3M6_B smuggler one (this one is just planned), so they could be shown in inventory like the occult skull key.

>Still necessary for the surrendering soldier key. --N00b

- [x] C1M6 has a scripted fight between cultists and Wehrmacht soldiers, and it goes well except on Mein Leben, where they do not deal any damage to each other (you can see this around 03:30 in part XIII), the sight is pretty weird. Can we do anything about this?
- [x] Please also add stepping on bats and/or fix their behaviour as seen near 00:50 in C2 part 23.
- [x] Starting from 04:50 in C2 part 30, you can see my attempts to get the yellow Astrostein keycard. Four Tiger robots spam their fast homing projectiles, and as a result it is quite difficult to survive even one or two block lowering/raising phases. I could get through this only savescumming, and I think this fight might possibly be the toughest in all of BoA.
I suggest to lower the homing speed and the movement speed of the projectiles slightly and add more health to the surrounding area with shotgun guards (in form of medikits and field kits).
- [x] C2 part 31, 09:55 (entrance to K. I. Kortex): non-moving Tiger robots.
- [x] In C2M1 snipers in the towers disappear after being stabbed (10:50 of C2 part II).
- [x] On Mein Leben, some enemies like melee mutants and scorpions just stand still. They still attack in melee AFAIK.<details>
This can be seen near 07:50 in part 2 of my C1 playthrough, 01:30 in part 8, and 05:20 in part 13 (scorpions), and you can also easily see this for yourself in any maps that contain melee mutants or yellow scorpions. @AFADoomer @Ozymandias81 @Talon1024, could any of you please investigate the matter? Posting this as a separate issue because @Tormentor667 asked me to do so.</details>

**Comment by Talon1024** [comment] 2020-09-28 20:35
I see the problem. The aggressiveness on "Mein Leben" is set to 1.0 (maximum), and so the mutants are always trying to do their ranged attack. However, the A_CheckLOF on [line 83](https://github.com/Realm667/WolfenDoom/blob/master/actors/monsters/mutants.txt#L83) prevents the ranged attack if the player is within 512 units of the mutant. So the mutant is going to the "see" state instead of moving towards the player.

**Comment by Username-N00b-is-not-available** [comment] 2020-09-29 07:17
- [ ] The Übermutant in the ending of C1M0 has way more health than suggested by his healthbar, you can unload several shotgun shots into him, and the healthbar will still be full.

**Comment by Tormentor667** [comment] 2020-09-29 08:06
Well investigated 👍

**Comment by Talon1024** [comment] 2020-09-29 17:09
>     * [ ]  The Übermutant in the ending of C1M0 has way more health than suggested by his healthbar, you can unload several shotgun shots into him, and the healthbar will still be full.

Should be fixed in e556e5a6f220dffc84c63af3786624aaa61a91aa

**Comment by Talon1024** [comment] 2020-09-29 18:34
What do you think about removing the [splash damage caused by the smoke monster upon dying](https://github.com/Realm667/WolfenDoom/blob/master/actors/monsters/bosses.txt#L636)?

**Comment by Username-N00b-is-not-available** [comment] 2020-09-29 18:49
@Talon1024 Would appreciate it, had to reload saves on my melee-only playthrough multiple times because of that :-)
Almost 400 dmg is way too much for an effect like this, and I think we lose nothing if we remove it altogether.

**Comment by Tormentor667** [comment] 2020-09-29 19:26
Agreed, that's fine.

**Comment by Username-N00b-is-not-available** [comment] 2020-09-29 20:49
I think I need to draw attention to this. @Ozymandias81 @AFADoomer @Talon1024,

- [ ] Please remove the target intercept system for tanks or make the firing delay shorter.

This could be a nice mechanic but sadly now it works inadequately. High firing delay which we have now completely trivializes the missile evasion by players, at this point it would be much better to just remove the target leading whatsoever and use standard codepointers like A_SpawnProjectile or something similar.

**Comment by Username-N00b-is-not-available** [comment] 2020-09-30 20:07
Something more on tanks.

- [ ] Very minor, but I think it would be nice to add initial velocity to the muzzle flash and cloud, it can now spawn in the gun if the tank is moving:

![Screenshot_Doom_20200930_133906](https://user-images.githubusercontent.com/59409713/94732208-9ff74380-036e-11eb-8ae5-82bd1eb81baf.png)

- [ ] T-34-85 model is very large and high, it is bigger than Tiger almost by half. In reality these tanks had such dimension parameters (T-34-85 is left, Tiger is right):

Height: 2700 vs 3000
Width: 3000 vs 3705
Length (without turret): 6100 vs 6316

![](https://i-a.d-cd.net/8811cbes-960.jpg)

- [ ] For some reason 'kill monsters' does not massacre all the tanks on map, it kills them one by one. Quite strange.

**Comment by Username-N00b-is-not-available** [comment] 2020-10-03 06:11
A new portion of reports from my walkthrough videos being watched by @Tormentor667:

- [ ] Please also add stepping on bats and/or fix their behaviour as seen near 00:50 in C2 part 23.

- [ ] Starting from 04:50 in C2 part 30, you can see my attempts to get the yellow Astrostein keycard. Four Tiger robots spam their fast homing projectiles, and as a result it is quite difficult to survive even one or two block lowering/raising phases. I could get through this only savescumming, and I think this fight might possibly be the toughest in all of BoA.
I suggest to lower the homing speed and the movement speed of the projectiles slightly and add more health to the surrounding area with shotgun guards (in form of medikits and field kits).

- [ ] C2 part 31, 09:55 (entrance to K. I. Kortex): non-moving Tiger robots.

**Comment by Tormentor667** [comment] 2020-10-03 07:36
Additional hint for the Tiger tanks at the yellow key in Astrostein: This only is happening in the harfest difficulty, the others are ok.

**Comment by Username-N00b-is-not-available** [comment] 2020-10-06 06:49
- [ ] Spies which give you items do not control if your inventory is full, e.g. if you already have 5 bandages and the spy gives you one, it is wasted. Same goes for 9mm ammo. Please add a check so in such situation the spy would just drop the item near player, so they can return and reclaim it later, when they need it.

**Comment by Talon1024** [comment] 2020-10-12 18:33
What do you guys think about setting a limit on the number of times the MutantMelee can throw his two cleavers? For example, how about making him only able to use that attack once or twice?

**Comment by Username-N00b-is-not-available** [comment] 2020-10-12 20:35
@Talon1024 Personally I think this is not a bad idea, since after the fixes they just spam these on Mein Leben... but it could make them helpless in a situation where the player can get into a safe spot (e.g. on a crate in C1M0). IMO it might be better to limit the frequency of the ranged attack.
Or if you are thinking about realism (where would they get so many cleavers), we can make the projectiles ricochet off solid surfaces and return to their owner like a boomerang, and the mutant will be able to rethrow the cleaver only when it has returned :-D BTW, their sprites will still have two cleavers in them, then we'll need to add cleaverless sprites.

**Comment by Tormentor667** [comment] 2020-10-13 05:41
This is a good idea :)

**Comment by Ozymandias81** [comment] 2020-10-13 17:50
All cool okay, but I would prefer to keep things as they are, in the end mutants with cleavers exists in Wolf3d since ages... so better not add a new feature and risk again to lose time over it to understand how to fix this/that then fall in "unforeseen consequences" with a new GZDoom build.

**Comment by Talon1024** [comment] 2020-10-13 20:30
Decreasing the frequency of the cleaver throw attack is a good idea. Maybe I can add some randomness to A_MeleeMutantChase. However, my idea wasn't to have them throw ALL of their cleavers... They have 1-3 pairs of spare cleavers for throwing, and their main pair of cleavers for melee.

**Comment by Tormentor667** [comment] 2020-10-18 10:20
Moved all the issues to the initial post so we don't miss anything.

**Comment by Talon1024** [comment] 2020-10-25 22:09
I'd like to make some more enemies, like the grenadiers and MG turrets, use the weaker explosion (GeneralExplosion_Nazis).

**Comment by Tormentor667** [comment] 2020-11-14 15:16
@Username-N00b-is-not-available AFAIK, you have added the surrenderer key, didn't you? The latter is just fine to use also the occult skull key, as that's the place where it gets inserted.

> Would be nice to add some sprites for the **C3M5_A surrendering soldier key** and also **C3M6_B smuggler one** (this one is just planned), so they could be shown in inventory like the occult skull key.

**Comment by Username-N00b-is-not-available** [comment] 2020-11-14 16:59
@Tormentor667 Oh, sorry, for some reason I thought I've closed that checkbox, but forgot to do so, please never mind it. Now everything with it is okay.
I meant Fritz Hosenscheisser there, because the checkbox is old, and IIRC in the beginning we named the SS merchant 'a smuggler'.

**Comment by Tormentor667** [comment] 2020-11-14 17:39
Thanks for clarifiying :)

**Closed** 2020-11-15 11:35 UTC
Labels: bug, gameplay, help wanted
