### ISSUE TITLE
[3.2] Safe door problems

### ISSUE THREAD

**Issue by x3003** [Realm667/WolfenDoom#772] opened 2021-06-06 14:34 UTC
If you fail to open the safe, the next time you press the use key, it shortly brings up the safe door / lock again, but closes the display again soon after. So you can't give it another try.

![Screenshot_Doom_20210606_162342](https://user-images.githubusercontent.com/77861029/120928226-0abe0300-c6e4-11eb-831e-194e904ee3f6.png)

I've seen it here as well: https://youtu.be/Y4Op81IadD8?t=3835

**Comment by AFADoomer** [comment] 2021-06-06 15:01
I can't recreate this in the current build...  Do you have specific instructions for recreating this?

Safes were reworked slightly after 3.0 release to make the interface easier, but I don't know what could be causing the problem seen in the video.

**Comment by x3003** [comment] 2021-06-06 15:10
Just give in a wrong code and press use or enter. After that when you try to work the safe again, the safe display doesn't stay up (later it works again).

**Comment by MuadDib90** [comment] 2021-06-06 15:50
I am remembering to encounter the problem presented here, but on a built before v3.0 release. In v3.0 and after I couldn't recreate this anymore...

Well maybe the "bug" stayed in v3.0 somehow, but as @AFADoomer said, the logic was adjusted after. All I can say now, I can no longer do it. (So I guess it is a version specific history thing...)

**Comment by x3003** [comment] 2021-06-06 17:33
Hmm, strange I can reproduce it every time. Also had 1 gzdoom crash while trying, but I can't reproduce that one anymore.

**Comment by MuadDib90** [comment] 2021-06-06 17:51
Well, the fact is, I didn't try that on purpose (with pre 27, or after it), it just didn't happened to me after the v3 release, because I knew about it, and back then I couldn't recreate it when testing, so I thought it was resolved.

I'll try it...

**Comment by x3003** [comment] 2021-06-06 18:25
>And I guess it is meaningless to test any no-up-to-date commit at this point. 

Well everything **is** up-to-date, even the drivers.

**Comment by MuadDib90** [comment] 2021-06-06 18:52
Phew... idk what to do then, to "experience" it, to help it resolve.

**Comment by AFADoomer** [comment] 2021-06-06 18:56
I have tried many times to recreate this...  Intentional wrong combos, random spinning, pressing enter many times in the wrong place, not pressing enter at all, etc., and haven't been able to reproduce this.

**Comment by Tormentor667** [comment] 2021-06-06 19:26
@x3003 can you create a clean installation and retry?

**Comment by Username-N00b-is-not-available** [comment] 2021-06-07 12:54
Can confirm something like this happened on C1M4 before 3.0: https://github.com/Realm667/WolfenDoom/issues/384#issuecomment-826332511, I could also not reproduce it. Maybe some GZDoom glitch...

**Comment by x3003** [comment] 2021-06-07 18:17
It's not about opening the safe. Just give in a wrong combo, enter and step away from the safe. Then try again pressing the use key.
And yes, I even have it on a fresh profile with opengl instead of vulkan.

**Comment by MuadDib90** [comment] 2021-06-07 18:24
> 
> 
> It's not about opening the safe. Just give in a wrong combo, enter and step away from the safe. Then try again pressing the use key.
> And yes, I even have it on a fresh profile with opengl instead of vulkan.

I know **exactly** what you are talking about, trust me, but I am still unable to do it (as I was able in the past)... I am really sorry. :(

**Comment by Talon1024** [comment] 2021-06-07 19:53
Does this still happen after opening and closing the main menu (ESC while ingame)?

**Comment by x3003** [comment] 2021-06-13 20:00
>Does this still happen after opening and closing the main menu (ESC while ingame)?

I think so. I also saved to a file (using ESC and the menu). It doesn't happen if you play on a while and come back to the safe.

**Comment by Tormentor667** [comment] 2021-06-20 11:39
This is certainly strange. I tried all three safes now and wasn't able to reproduce this.

**Comment by Username-N00b-is-not-available** [comment] 2021-06-20 18:25
It seems this is another ghost bug which appears and disappears arbitrarily, possibly because of GZDoom/hardware quirks. Well, at least this one can be circumvented. I think this is better left for 3.2.

**Comment by Tormentor667** [comment] 2021-06-20 18:41
We should make sure to only playtest this with the latest stable release.

**Comment by Tormentor667** [comment] 2021-06-26 17:34
We never had similar reports from other players so I simply will close this for now.

**Closed by Tormentor667** 2021-06-26 17:34 UTC
Labels: actor, playtesting, zscript
