### ISSUE TITLE
C2M3 issue

### ISSUE THREAD

**Issue by hawkwind3** [Realm667/WolfenDoom#875] opened 2021-06-21 03:50 UTC
See screenshot. Note door on right.
![Screenshot_BoA_20210621_130429](https://user-images.githubusercontent.com/35204218/122704769-ad0ae880-d297-11eb-98b2-26fffb12fa3e.jpg)

**Comment by Username-N00b-is-not-available** [comment] 2021-06-21 07:58
Duplicate (see archive in #844) and already fixed by @Tormentor667 yesterday.

**Closed by Username-N00b-is-not-available** 2021-06-21 07:58 UTC

**Comment by hawkwind3** [comment] 2021-06-21 12:36
No mention of this in #844, but if definitely fixed, well and good.

**Comment by Username-N00b-is-not-available** [comment] 2021-06-21 12:51
@hawkwind3 There is a mention (in the 'Resolved issues archive'), open the spoiler there and Ctrl+F "Problems with door offsets". It is checked. Here's an in-game screenshot from the current build:
![Screenshot_BoA_20210621_155107](https://user-images.githubusercontent.com/59409713/122764817-87d2a600-d2a8-11eb-8452-4674e386ef3a.png)
It's just that such long issues for the whole episode are by design messy, and putting what has already been fixed into an archive at least reduces the visible clutter.

**Comment by hawkwind3** [comment] 2021-06-21 13:09
Sorry for my ignorance, but where is the resolved issues archive ? Would help me for future reports.

**Comment by Username-N00b-is-not-available** [comment] 2021-06-21 13:14
@hawkwind3 For #844, it is in the original post, closer to its ending part:
![image](https://user-images.githubusercontent.com/59409713/122767665-8fe01500-d2ab-11eb-94be-087944cac1bb.png)
I'll also open such 'archives' in #824 and #863 when more issues are fixed there.

**Comment by hawkwind3** [comment] 2021-06-21 13:22
Thanks for that. I understand now.
